### ISSUE TITLE
【漏洞】{获取专栏内容时显示列表超出范围}

### ISSUE THREAD

**Issue by scp23328** [Nemo2011/bilibili-api#137]
**Python 版本： 3.9.12 

**模块版本：14.0.0.rc

**运行环境： Windows

**模块路径：bilibili_api.article`

**解释器：pypi

**报错信息：**

```
Traceback (most recent call last):
  File "G:\bilizhuanlanshoucang\venv\main.py", line 114, in <module>
    sync(main())
  File "G:\bilizhuanlanshoucang\venv\lib\site-packages\bilibili_api\utils\sync.py", line 32, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\bilizhuanlanshoucang\venv\main.py", line 32, in main
    await ar.fetch_content()
  File "G:\bilizhuanlanshoucang\venv\lib\site-packages\bilibili_api\article.py", line 397, in fetch_content
    self.__children = parse(document.find("div"))
  File "G:\bilizhuanlanshoucang\venv\lib\site-packages\bilibili_api\article.py", line 196, in parse
    node.children = parse(e)
  File "G:\bilizhuanlanshoucang\venv\lib\site-packages\bilibili_api\article.py", line 378, in parse
    node.text = e.contents[0]
IndexError: list index out of range

```

**报错代码：**

```
这里填写报错代码
```

---

代码如下
ddd=await favorite_list.get_article_favorite_list(p,credential=credential)
        # for xyz in range(20):
        #     ffc=ddd['favorites'][xyz]['id']
        #     # ffcc=int(ffc)
        ar = article.Article(21066880)

        await ar.fetch_content()
        df=ar.json()
        print(df)
我在尝试获取21066880与20998764这两个专栏的内容时发生列表越界

**Comment by z0z0r4** [comment]
dev 分支可用，请等待 main 分支更新...23333
![image](https://user-images.githubusercontent.com/78744121/212368958-08aebfb6-efdd-4c81-89b4-c04bff4e802f.png)

**Comment by Nemo2011** [comment]
我做过测试了，`14.0.0.rc` 爬取数据没有问题啊。

**Comment by Nemo2011** [comment]
这个错误早就修复了，难道是我的 `14.0.0.rc` 的安装包打错了？

**Comment by Nemo2011** [comment]
你确定你的版本是 `14.0.0.rc`?

**Comment by scp23328** [comment]
14.0.0.rc是没问题的，但我clone下来的是13.3.1的包，不知道是怎么回事

**Comment by Nemo2011** [comment]
`main` 分支放的是稳定版本，`dev` 分支放的才是预发布版本和线上仓库实时最新版本。所以 `clone` 下来 `main` 分支后是 `13.3.1` 版本。

**Comment by Nemo2011** [comment]
我这里用的是 `python` 的大环境和 `pip` 进行 `14.0.0.rc` 的安装的，结果没有出现你提到的问题。难道是  conda forge 的问题？你看一下你的 `bilibili_api` 有没有 `note` 模块。如果有的话就代表你的确是 `14.0.0.rc`，否则你就是在 `14.0.0.rc` 之前的版本了。

**Comment by scp23328** [comment]
我clone下来就直接用了，确实是13.3.1版本，新版本没有问题

**Comment by z0z0r4** [comment]
可以close了
