### ISSUE TITLE
【漏洞】新版用户合集初始化失败

### ISSUE THREAD

**Issue by scp23328** [Nemo2011/bilibili-api#142]
**Python 版本：3.10

**模块版本：14.0.0.rc

**运行环境： Windows

在我获取用户合集信息时发生报错，因为我是python初学者，不太确定此问题是我的代码问题还是其他原因
代码
from bilibili_api import user,sync
import json

userchannelid=976485

Ch = user.ChannelSeriesType.SEASON
id=14392124
async def main():
    uu=user.ChannelSeries(id,Ch,userchannelid)
    u = await user.ChannelSeries.get_videos(uu)
    # channel=await u.get_videos()
    print(u)
sync(main())

报错提示

Traceback (most recent call last):
  File "G:\biliheji\venv\main.py", line 14, in <module>
    sync(main())
  File "G:\biliheji\venv\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\biliheji\venv\main.py", line 10, in main
    uu=user.ChannelSeries(id,Ch,userchannelid)
  File "G:\biliheji\venv\lib\site-packages\bilibili_api\user.py", line 948, in __init__
    self.meta["mid"] = resp["upper"]["mid"]
KeyError: 'upper'
希望大佬们能帮忙看一下，万分感谢

**Comment by Nemo2011** [comment]
忘记打了键值的锅……这样子，你可以先把报错中的 `self.meta["mid"] = resp["upper"]["mid"]` 改成 `self.meta["mid"] = resp["info"]["upper"]["mid"]`，这样子可以解决问题，最新版本会对这个错误作出修复。如果你这里情况紧急的话我可以先弄一个 hotfix。

**Comment by Nemo2011** [comment]
修改代码具体就是找到报错文件的对应行数，然后修改那一行的对应的代码。

**Comment by scp23328** [comment]
没事，我自己修就行了

**Comment by scp23328** [comment]
另外问一个问题，我在爬取专栏内容爬到一半时会报如下错误
Traceback (most recent call last):
  File "G:\bilibilizhuanlan\venv\main.py", line 55, in <module>
    sync(main())
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\utils\sync.py", line 32, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\bilibilizhuanlan\venv\main.py", line 36, in main
    await zhuanlan.fetch_content()
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\article.py", line 397, in fetch_content
    self.__children = parse(document.find("div"))
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\article.py", line 339, in parse
    if figcaption_el.contents:
AttributeError: 'NoneType' object has no attribute 'contents'
代码如下
from bilibili_api import article, sync,Credential
import json
from jsonsearch import JsonSearch

rl = 637375
async def main():
    # 获取文章
    xyz=0
    xzz=0
    listid=[]
    abd =article.ArticleList(513843)
    c=await abd.get_content()
    json_dict_2 = json.dumps(c, indent=2, sort_keys=False, ensure_ascii=False)

    jsondata = JsonSearch(object=json_dict_2, mode='s')
    idd = jsondata.search_all_value(key='id')
    leng=len(idd)
    for xyz in range(leng):
        if idd[xyz]<1000000 :
            continue
        else:
            listid.append(idd[xyz])
            lengid=len(listid)
        for xzz in range(lengid):
            zhuanlan=article.Article(listid[xzz])
            await zhuanlan.fetch_content()
            df=zhuanlan.json()
            json_dict_3 = json.dumps(df, indent=2, sort_keys=False, ensure_ascii=False)

            jsondata = JsonSearch(object=json_dict_3, mode='s')
            url = jsondata.search_all_value(key='url')
            print(listid[xzz])
            print(url)
    print(len(listid))
    print(listid)

sync(main())
请问是什么情况？

**Comment by Nemo2011** [comment]
你要不先换到另一个 issues 说？

**Comment by Nemo2011** [comment]
目前 `dev` 分支已经完成了修改，我也亲自运行过了，没有问题。
