### ISSUE TITLE
【建议】专栏爬取问题

### ISSUE THREAD

**Issue by scp23328** [Nemo2011/bilibili-api#144]
我在爬取专栏内容时会报如下错误
Traceback (most recent call last):
  File "G:\bilibilizhuanlan\venv\main.py", line 37, in <module>
    sync(main())
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\bilibilizhuanlan\venv\main.py", line 25, in main
    zhuanlan=article.Article(listid[xzz])
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\article.py", line 139, in __init__
    if resp["data"]["type"] == 0:
TypeError: 'NoneType' object is not subscriptable
代码如下
from bilibili_api import article, sync,Credential
import json
from jsonsearch import JsonSearch

rl = 637375
async def main():
    # 获取文章
    xyz=0
    xzz=0
    listid=[]
    abd =article.ArticleList(513843)
    c=await abd.get_content()
    json_dict_2 = json.dumps(c, indent=2, sort_keys=False, ensure_ascii=False)

    jsondata = JsonSearch(object=json_dict_2, mode='s')
    idd = jsondata.search_all_value(key='id')
    leng=len(idd)
    for xyz in range(leng):
        if idd[xyz]<1000000 :
            continue
        else:
            listid.append(idd[xyz])
            lengid=len(listid)
        for xzz in range(lengid):
            zhuanlan=article.Article(listid[xzz])
            await zhuanlan.fetch_content()
            df=zhuanlan.json()
            json_dict_3 = json.dumps(df, indent=2, sort_keys=False, ensure_ascii=False)

            jsondata = JsonSearch(object=json_dict_3, mode='s')
            url = jsondata.search_all_value(key='url')
            print(listid[xzz])
            print(url)
    print(len(listid))
    print(listid)

sync(main())
请问是什么情况？

**Comment by Nemo2011** [comment]
就是 bilibili 专栏的 html 元素中的奇葩种太多了，都识别不过来了。目前 `dev` 分支已经改好了，你可以 clone 下来后安装 `dev` 版本。

**Comment by scp23328** [comment]
另外问一下，
 File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\article.py", line 528, in fetch_content
    self.__children = await parse(document.find("div")) # type: ignore
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\article.py", line 323, in parse
    if "class" in img_el.attrs:
AttributeError: 'NoneType' object has no attribute 'attrs'
这种专栏报错也是因为专栏内有特殊元素吗？

**Comment by Nemo2011** [comment]
你当时在爬取的专栏是哪一个专栏

**Comment by scp23328** [comment]
cv10079503

**Comment by Nemo2011** [comment]
https://github.com/Nemo2011/bilibili-api/commit/14f85c70e5e61cf3754c911b1a46de2b747ec3be 已解决。
