### ISSUE TITLE
【漏洞】{专栏内容无法获取}

### ISSUE THREAD

**Issue by scp23328** [Nemo2011/bilibili-api#166]
**Python 版本：** 3.10

**模块版本：** 14.2

**运行环境：** Windows 

**模块路径：`bilibili_api.article

**解释器：** cpython

**报错信息：**
Traceback (most recent call last):
  File "G:\bilibilizhuanlan\venv\test.py", line 15, in <module>
    sync(main())
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\bilibilizhuanlan\venv\test.py", line 13, in main
    await zhuanlan.fetch_content()
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\article.py", line 529, in fetch_content
    self.__children = await parse(document.find("div")) # type: ignore
  File "G:\bilibilizhuanlan\venv\lib\site-packages\bilibili_api\article.py", line 462, in parse
    className = e.attrs["class"]
KeyError: 'class'

**报错代码：**
async def main():
    zhuanlan=article.Article(7592102)
    await zhuanlan.fetch_content()
    df=zhuanlan.json()
---

在获取专栏cv7592102的内容时发生如上报错，完全无法获取专栏内容

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/b49dc5ac830507bcfa82cef3c65ccca83ace06ae/bilibili_api/article.py#L463
```diff
- className = e.attrs["class"]
+ className = e.attrs.get("class", "")
```
经测试可解决此问题，但该模块中多次使用了类似的直接取值，建议修改为 `e.attrs.get()` 并判断。

**Comment by Nemo2011** [comment]
其他的 `e.attrs["xxx"]` 貌似都有 `if "xxx" in e.attrs.keys()` 的判断
