### ISSUE TITLE
【提问】{使用dynamic.upload_image经常出现如下报错}

### ISSUE THREAD

**Issue by MEYUYU** [Nemo2011/bilibili-api#198]
**Python 版本：** 3.8.0

**模块版本：** 15.0.0

**运行环境：** Windows

---

上传动态图片
测试如下代码:

```from bilibili_api import dynamic, Credential, Picture
import asyncio

async def main() -> None:
    credential = ********
    resp = await dynamic.upload_image(image=Picture.from_file('./dynamic.png'),credential=credential)
    print(resp)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

经常出现如下报错:

```
Traceback (most recent call last):
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\backends\asyncio.py", line 51, in write
    await self._stream.send(item=buffer)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\anyio\streams\tls.py", line 178, in send
    await self._call_sslobject_method(self._ssl_object.write, item)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\anyio\streams\tls.py", line 144, in _call_sslobject_method
    await self.transport_stream.send(self._write_bio.read())
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\anyio\_backends\_asyncio.py", line 1147, in send
    await self._protocol.write_event.wait()
  File "C:\Program Files\python\lib\asyncio\locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\backends\asyncio.py", line 51, in write
    await self._stream.send(item=buffer)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\anyio\_core\_tasks.py", line 103, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_async\http11.py", line 82, in handle_async_request
    await self._send_request_body(**kwargs)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_async\http11.py", line 135, in _send_request_body
    await self._send_event(event, timeout=timeout)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_async\http11.py", line 144, in _send_event
    await self._network_stream.write(bytes_to_send, timeout=timeout)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\backends\asyncio.py", line 51, in write
    await self._stream.send(item=buffer)
  File "C:\Program Files\python\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.WriteTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\b.py", line 11, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\python\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File ".\b.py", line 7, in main
    resp = await dynamic.upload_image(image=Picture.from_file('./dynamic.png'),credential=credential)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\bilibili_api\dynamic.py", line 110, in upload_image
    return_info = await request(
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\bilibili_api\utils\network_httpx.py", line 127, in request
    resp = await session.request(**config)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_client.py", line 1722, in _send_single_request    response = await transport.handle_async_request(request)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Program Files\python\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\ZZZ\AppData\Roaming\Python\Python38\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.WriteTimeout
```

多出现在大于10M的图片上传,使用同一台电脑的网页发送动态都没有问题

**Comment by Nemo2011** [comment]
文件太大超过 timeout 了，你先试一下设置 timeout（settings 模块中），设的时间长一点。

**Comment by MEYUYU** [comment]
尝试修改timeout,设置成60.0,效果并不明显,依然无法上传大尺寸图片,相同的报错

**Comment by MEYUYU** [comment]
> 文件太大超过 timeout 了，你先试一下设置 timeout（settings 模块中），设的时间长一点。

尝试修改timeout,设置成60.0,效果并不明显,依然无法上传大尺寸图片,相同的报错

**Comment by MEYUYU** [comment]
尝试直接修改httpx的默认timeout,问题得到解决
