### ISSUE TITLE
【漏洞】user.get_live_info 接口失败

### ISSUE THREAD

**Issue by USN484259** [Nemo2011/bilibili-api#262]
**Python 版本：** Python 3.10.6

**模块版本：** 15.1.0 

**运行环境：** Ubuntu 22.04, Linux 5.15.0-70-generic x86_64

**模块路径：** `bilibili_api.user`

**解释器：** cpython

**报错信息：**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usn484259/.local/lib/python3.10/site-packages/bilibili_api/utils/sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/usn484259/.local/lib/python3.10/site-packages/bilibili_api/user.py", line 322, in get_live_info
    return await request(
  File "/home/usn484259/.local/lib/python3.10/site-packages/bilibili_api/utils/network_httpx.py", line 152, in request
    resp_data = json.loads(raw_data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)
```

**报错代码：**

```
$ python3
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bilibili_api import user, sync
>>> u = user.User(508963009)
>>> info = sync(u.get_live_info())

```

---

调用`user.get_live_info`接口时产生异常 `json.decoder.JSONDecodeError`
在 2023年4月20日首次观察到该问题。从本地直播推送脚本的行为判断，4月19日无该问题/出现概率较低
在Ubuntu 20.04 with Python3.8 和 Ubuntu 22.04 with Python3.10 测试，该问题不是必现，但概率较大，也可能和特定up主页面有关。怀疑是B站接口改动引起的

**Comment by USN484259** [comment]
在`utils/network_httpx.py`的`request`函数中打印出`raw_data`，样例如下：
```
{"code":-509,"message":"请求过于频繁，请稍后再试","ttl":1}{"code":0,"message":"0","ttl":1,"data":{"mid":508963009,"name":"HiiroVTuber","sex":"保密","face":"https://i1.hdslb.com/bfs/face/7a41310afc08381ad0451bee8ea07f15fcc411bd.jpg","face_nft":0,"face_nft_type":0,"sign":"901 IQ, 不是 425KG 的 debu, cat！在学中文【直播是晚上8点，在动态通知】","rank":10000,"level":6,"jointime":0,"moral":0,"silence":0,"coins":0,"fans_badge":true,"fans_medal":{"show":false,"wear":false,"medal":null},"official":{"role":7,"title":"bilibili 直播高能主播","desc":"","type":0},"vip":{"type":2,"status":1,"due_date":1875628800000,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"年度大会员","label_theme":"annual_vip","text_color":"#FFFFFF","bg_style":1,"bg_color":"#FB7299","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/8d4f8bfc713826a5412a0a27eaaac4d6b9ede1d9.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/VEW8fCC0hg.png"},"avatar_subscript":1,"nickname_color":"#FB7299","role":3,"avatar_subscript_url":"","tv_vip_status":0,"tv_vip_pay_type":0},"pendant":{"pid":4357,"name":"希萝Hiiro","image":"https://i1.hdslb.com/bfs/garb/item/afa6dc89047b1fc86a72996a4890d44871f8896e.png","expire":0,"image_enhance":"https://i1.hdslb.com/bfs/garb/item/afa6dc89047b1fc86a72996a4890d44871f8896e.png","image_enhance_frame":""},"nameplate":{"nid":1,"name":"黄金殿堂","image":"https://i2.hdslb.com/bfs/face/82896ff40fcb4e7c7259cb98056975830cb55695.png","image_small":"https://i0.hdslb.com/bfs/face/627e342851dfda6fe7380c2fa0cbd7fae2e61533.png","level":"稀有勋章","condition":"单个自制视频总播放数\u003e=100万"},"user_honour_info":{"mid":0,"colour":null,"tags":[]},"is_followed":false,"top_photo":"http://i0.hdslb.com/bfs/space/cb1c3ef50e22b6096fde67febe863494caefebad.png","theme":{},"sys_notice":{},"live_room":{"roomStatus":1,"liveStatus":0,"url":"https://live.bilibili.com/21919321?broadcast_type=0\u0026is_room_feed=1","title":"坏了刚醒","cover":"http://i0.hdslb.com/bfs/live/new_room_cover/c1eab82d56f1fb390d7fce967c781fefca0563da.jpg","roomid":21919321,"roundStatus":1,"broadcast_type":0,"watched_show":{"switch":true,"num":5254,"text_small":"5254","text_large":"5254人看过","icon":"https://i0.hdslb.com/bfs/live/a725a9e61242ef44d764ac911691a7ce07f36c1d.png","icon_location":"","icon_web":"https://i0.hdslb.com/bfs/live/8d9d0f33ef8bf6f308742752d13dd0df731df19c.png"}},"birthday":"","school":null,"profession":{"name":"","department":"","title":"","is_show":0},"tags":null,"series":{"user_upgrade_status":3,"show_upgrade_window":false},"is_senior_member":0,"mcn_info":null,"gaia_res_type":0,"gaia_data":null,"is_risk":false,"elec":{"show_info":{"show":true,"state":1,"title":"","icon":"","jump_url":""}},"contract":null}}
```
可以看出问题原因是B站限流。但是该处代码没有正确识别限流场景，导致抛出的异常与实际错误不一致

**Comment by Drelf2018** [comment]
https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/data/api/user.json#L93
```diff
- "url": "https://api.bilibili.com/x/space/acc/info",
+ "url": "https://api.bilibili.com/x/space/wbi/acc/info",
```
可暂时解决问题，具体修复等待下次更新。

**Comment by dongruixiao** [comment]
get_user_info 接口也是这个报错

**Comment by Drelf2018** [comment]
> get_user_info 接口也是这个报错，可以一并修一下

https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/data/api/user.json#L30

居然写了两个一样的接口，感觉要去掉一个啊。

**Comment by z0z0r4** [comment]
> > get_user_info 接口也是这个报错，可以一并修一下
> 
> https://github.com/Nemo2011/bilibili-api/blob/main/bilibili_api/data/api/user.json#L30
> 
> 居然写了两个一样的接口，感觉要去掉一个啊。

已经是上一任 owner 的坑了

![image](https://user-images.githubusercontent.com/78744121/233689559-1643b662-7a5b-490d-a5f5-e2d8ff112a16.png)

**Comment by HoshimiStellae** [comment]
user.get_videos()也出现同样报错😭

**Comment by Nemo2011** [comment]
很可能现在是 `https://api.bilibili.com/x/space/***` -> `https://api.bilibili.com/x/space/wbi/***`

**Comment by Nemo2011** [comment]
`https://api.bilibili.com/x/space/wbi/arc/search`

**Comment by z0z0r4** [comment]
> https://api.bilibili.com/x/space/***

不确定，起码 `https://api.bilibili.com/x/space/myinfo` -> `https://api.bilibili.com/x/space/wbi/myinfo` 不存在...

另外 action 好像登录凭据炸了

**Comment by z0z0r4** [comment]
现往 https://github.com/Nemo2011/bilibili-api/issues/290 汇总
