### ISSUE TITLE
【提问】上传视频接口报错：406 - Not Acceptable

### ISSUE THREAD

**Issue by douloveppt** [Nemo2011/bilibili-api#265]
**Python 版本：** 3.11

**模块版本：** Lastest

**运行环境：**MacOS

---

上传视频模块video_uploader，我上传9个视频，每传一个会等待三分钟左右，传到第五个的时候报错了

Traceback (most recent call last):
  File "/Users/bibowang/Documents/workspace/demo/auto_up/upload.py", line 73, in <module>
    sync(upload_videos())
  File "/Users/bibowang/Documents/workspace/venv/lib/python3.11/site-packages/bilibili_api/utils/sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bibowang/Documents/workspace/demo/auto_up/upload.py", line 66, in upload_videos
    await uploader.start()
  File "/Users/bibowang/Documents/workspace/venv/lib/python3.11/site-packages/bilibili_api/video_uploader.py", line 453, in start
    raise e
  File "/Users/bibowang/Documents/workspace/venv/lib/python3.11/site-packages/bilibili_api/video_uploader.py", line 445, in start
    result = await task
             ^^^^^^^^^^
  File "/Users/bibowang/Documents/workspace/venv/lib/python3.11/site-packages/bilibili_api/video_uploader.py", line 413, in _main
    data = await self._upload_page(page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bibowang/Documents/workspace/venv/lib/python3.11/site-packages/bilibili_api/video_uploader.py", line 487, in _upload_page
    preupload = await self._preupload(page)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bibowang/Documents/workspace/venv/lib/python3.11/site-packages/bilibili_api/video_uploader.py", line 250, in _preupload
    raise NetworkException(resp.status_code, resp.reason_phrase)
bilibili_api.exceptions.NetworkException.NetworkException: 网络错误，状态码：406 - Not Acceptable。

大佬帮忙看下~，感恩~~~

**Comment by douloveppt** [comment]
上传代码如下：

**Comment by Nemo2011** [comment]
建议重新进行尝试

**Comment by douloveppt** [comment]
> 建议重新进行尝试，把第五个视频单独拆开来进行多次重复上传，看是否有问题。

还是不行，应该不是视频的原因，我试了其他好几个视频都是报的NetworkException: 网络错误，状态码：406 - Not Acceptable。换代理IP也不行，不知道是不是账号被封了的原因，但是页面上又可以正常登录。

**Comment by xzh12** [comment]
账号应该是被封了，找客服让他们解开就行了

**Comment by douloveppt** [comment]
> 账号应该是被封了，找客服让他们解开就行了

账号封了页面上应该也登录不了吧

**Comment by xzh12** [comment]
你只是被他们的技术封了上传的权限

**Comment by douloveppt** [comment]
> 你只是被他们的技术封了上传的权限

那客服也不会帮处理吧

**Comment by xzh12** [comment]
会处理的

**Comment by Alkaid-C** [comment]
> 账号应该是被封了，找客服让他们解开就行了

好吧，我又遇到这个问题了。你说账号被封了，可问题是我手动用网页上传是可以正常上传的。请问我怎么跟客服说呢？我总不能说网页ok但是调api不ok吧？
