### ISSUE TITLE
【漏洞】user.get_videos()方法返回一个错误，提示json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by WindowsSov8forUs** [Nemo2011/bilibili-api#278]
**Python 版本：** 3.11.2

**模块版本：** 15.3.1

**运行环境：** Windows

**模块路径：** `bilibili_api.user`

**解释器：** cpython

**报错信息：**

```
Traceback (most recent call last):
  File "f:\VS Code File\test\test_3.py", line 56, in <module>
    vlist = asyncio.run(user.get_videos())['list']['vlist']
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\bilibili_api\user.py", line 356, in get_videos
    return await request(
           ^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\bilibili_api\utils\network_httpx.py", line 152, in request
    resp_data = json.loads(raw_data)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)
```

**报错代码：**

```
uid = 10741206
user = User(uid, CREDENTIAL)
user_info = asyncio.run(user.get_user_info())
jsonWrite('test_3.json', user_info)
print(user_info['name'])
vlist = asyncio.run(user.get_videos())['list']['vlist']
```

---

很久以前就有的问题了，在调用```user.get_videos()```时出现```json.decoder.JSONDecodeError```问题，猜测可能与之前```user.get_live_info()```和```user.get_user_info()```的问题是类似的，但是问题是它并不是彻底不能使用，也不是一长段时间内存在这个问题，而是有时候可以获取，有时候不能获取，甚至有过相同代码连续三次运行只有第二次没有出现问题的情况和刚出现问题重新运行后又成功获取的情况

**Comment by Drelf2018** [comment]
应该是你提到的那个问题，这个问题在版本 `15.4.1` 修复了。尝试更新库，观察是否继续出现错误。

```python
pip install bilibili-api-python --upgrade
```

**Comment by WindowsSov8forUs** [comment]
> 

目前更新了之后是没出问题，谢谢

**Comment by z0z0r4** [comment]
close了
