### ISSUE TITLE
【漏洞】user.get_videos 解析 JSON response 错误

### ISSUE THREAD

**Issue by USN484259** [Nemo2011/bilibili-api#316]
**Python 版本：** Python 3.8.10

**模块版本：** 15.4.4 

**运行环境：** Ubuntu 20.04, Linux 5.15.0-72-generic x86_64

**模块路径：** `bilibili_api.user`

**解释器：** cpython

**报错信息：**

```
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    vl = sync(u.get_videos(pn = i))
  File "/home/usn484259/.local/lib/python3.8/site-packages/bilibili_api/utils/sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/usn484259/.local/lib/python3.8/site-packages/bilibili_api/user.py", line 360, in get_videos
    return await request(
  File "/home/usn484259/.local/lib/python3.8/site-packages/bilibili_api/utils/network_httpx.py", line 204, in request
    resp_data = json.loads(raw_data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 3500 (char 3499)
```

**报错代码：**

```
#!/usr/bin/env python3

from bilibili_api import user, sync
import time

u = user.User(11666085)

for i in range(1, 15):
	print(i)
	vl = sync(u.get_videos(pn = i))
	time.sleep(0.8)	# time.sleep(1)

```

---

在使用本地视频下载脚本时发现该问题，在 Ubuntu 22.04 with Python 3.10.6 和 Ununtu 20.04 with Python Python 3.8.10 都观察到该问题。

目前该问题复现概率较低，似乎只会在几个特定uid上发生（可能与视频投稿页数多有关）。在我的网络环境下验证，调用该接口的时间间隔在1秒左右时，多次运行以上代码可以复现问题。
将 utils/network_httpx.py line 194 的 raw_data 打印，问题发生时的样例如下，看起来像是数据接收不完全。

```
{"code":0,"message":"0","ttl":1,"data":{"list":{"tlist":{"1":{"tid":1,"count":284,"name":"动画"},"160":{"tid":160,"count":27,"name":"生活"},"217":{"tid":217,"count":15,"name":"动物圈"},"3":{"tid":3,"count":1,"name":"音乐"},"4":{"tid":4,"count":5,"name":"游戏"}},"vlist":[{"comment":7,"typeid":27,"play":7536,"pic":"http://i2.hdslb.com/bfs/archive/d9bdd98404098bb14553d9e0f5bdb5fbfbc52c12.jpg","subtitle":"","description":"HiiroVtuber 02/22直播自录\n粉色大猫猫hiiro的直播地址：https://live.bilibili.com/21919321\n粉色大猫猫hiiro的主页：https://space.bilibili.com/508963009","copyright":"2","title":"【hiiro】评价为对诺拉的拙劣模仿（x）","review":0,"author":"民工业","mid":11666085,"created":1677075575,"length":"00:33","video_review":3,"aid":609784214,"bvid":"BV1L84y1J76X","hide_click":false,"is_pay":0,"is_union_video":0,"is_steins_gate":0,"is_live_playback":0,"meta":{"id":1415911,"title":"Hiiro","cover":"https://archive.biliimg.com/bfs/archive/c2d24a31918ef4abbcc1c07a9aa8c34a1407cbd1.jpg","mid":11666085,"intro":"切片合集","sign_state":0,"attribute":140,"stat":{"season_id":1415911,"view":4683892,"danmaku":4316,"reply":8332,"favorite":25845,"coin":1603,"share":5870,"like":136992,"mtime":1685632937,"vt":7114229,"vv":0},"ep_count":283,"first_aid":826848591,"ptime":1685537220,"ep_num":0},"is_avoided":0,"attribute":0,"is_charging_arc":false},{"comment":10,"typeid":27,"play":6681,"pic":"http://i1.hdslb.com/bfs/archive/a92d7bc09bcd531a997f15f0adeb4cef8228bddc.jpg","subtitle":"","description":"HiiroVtuber 02/22直播自录\n粉色大猫猫hiiro的直播地址：https://live.bilibili.com/21919321\n粉色大猫猫hiiro的主页：https://space.bilibili.com/508963009","copyright":"2","title":"【hiiro】我 杀 我 自 己","review":0,"author":"民工业","mid":11666085,"created":1677075324,"length":"01:13","video_review":0,"aid":267373254,"bvid":"BV1gY411e7By","hide_click":false,"is_pay":0,"is_union_video":0,"is_steins_gate":0,"is_live_playback":0,"meta":{"id":1415911,"title":"Hiiro","cover":"https://archive.biliimg.com/bfs/archive/c2d24a31918ef4abbcc1c07a9aa8c34a1407cbd1.jpg","mid":11666085,"intro":"切片合集","sign_state":0,"attribute":140,"stat":{"season_id":1415911,"view":4683892,"danmaku":4316,"reply":8332,"favorite":25845,"coin":1603,"share":5870,"like":136992,"mtime":1685632937,"vt":7114229,"vv":0},"ep_count":283,"first_aid":826848591,"ptime":1685537220,"ep_num":0},"is_avoided":0,"attribute":0,"is_charging_arc":false},{"comment":18,"typeid":27,"play":5469,"pic":"http://i0.hdslb.com/bfs/archive/77032456afb88646e6b6cc36775978360b3587c0.jpg","subtitle":"","description":"HiiroVtuber 02/22直播自录\n粉色大猫猫hiiro的直播地址：https://live.bilibili.com/21919321\n粉色大猫猫hiiro的主页：https://space.bilibili.com/508963009","copyright":"2","title":"【hiiro】哎呀宝贝儿~ 一分钟循环","review":0,"author":"民工业","mid":11666085,"created":1677064915,"length":"01:02","video_review":5,"aid":479798594,"bvid":"BV1BM411c7vu","hide_click":false,"is_pay":0,"is_union_video":0,"is_steins_gate":0,"is_live_playback":0,"meta":{"id":1415911,"title":"Hiiro","cover":"https://archive.biliimg.com/bfs/archive/c2d24a31918ef4abbcc1c07a9aa8c34a1407cbd1.jpg","mid":11666085,"intro":"切片合集","sign_state":0,"attribute":140,"stat":{"season_id":1415911,"view":4683892,"danmaku":4316,"reply":8332,"favorite":25845,"coin":1603,"share":5870,"like":136992,"mtime":1685632937,"vt":7114229,"vv":0},"ep_count":283,"first_aid":826848591,"ptime":1685537220,"ep_num":0},"is_avoided":0,"attribute":0,"is_charging_arc":false},{"comment":6,"typeid":27,"play":19580,"pic":"http://i2.hdslb.com/bfs/archive/3802b8c2b932de4d4d74655b4606657bf500e838.jpg","subtitle":"","description":"HiiroVtuber 02/21直播自录\n粉色大猫猫hiiro的直播�
```

**Comment by Drelf2018** [comment]
本人环境在去掉 time.sleep 后多次尝试仍无法复现。推测可能与您的环境频繁访问被临时ban有关，但不排除函数确实有误的可能。

**Comment by Drelf2018** [comment]
确实存在获取数据缺失的问题，我的解决办法是捕获 `json.decoder.JSONDecodeError` 错误后就重新获取一次，一般第二次就能得到正确数据。或者等待新版本 `@retry` 装饰器应用在 `request` 函数上后，自动对这种情况重试。

**Comment by z0z0r4** [comment]
> 确实存在获取数据缺失的问题，我的解决办法是捕获 `json.decoder.JSONDecodeError` 错误后就重新获取一次，一般第二次就能得到正确数据。或者等待新版本 `@retry` 装饰器应用在 `request` 函数上后，自动对这种情况重试。

这是wbi鉴权导致的吗？还是常规 qos 限制…亦或单纯的 httpx 请求炸了？

**Comment by Drelf2018** [comment]
> > 确实存在获取数据缺失的问题，我的解决办法是捕获 `json.decoder.JSONDecodeError` 错误后就重新获取一次，一般第二次就能得到正确数据。或者等待新版本 `@retry` 装饰器应用在 `request` 函数上后，自动对这种情况重试。
> 
> 这是wbi鉴权导致的吗？还是常规 qos 限制…亦或单纯的 httpx 请求炸了？

单纯的数据太长了，这个接口返回数据普遍 30000 字符以上

**Comment by z0z0r4** [comment]
> > > 确实存在获取数据缺失的问题，我的解决办法是捕获 `json.decoder.JSONDecodeError` 错误后就重新获取一次，一般第二次就能得到正确数据。或者等待新版本 `@retry` 装饰器应用在 `request` 函数上后，自动对这种情况重试。
> > 
> > 这是wbi鉴权导致的吗？还是常规 qos 限制…亦或单纯的 httpx 请求炸了？
> 
> 单纯的数据太长了，这个接口返回数据普遍 30000 字符以上

诶…？太长，json库解不动？
感觉3w不多啊，py这么拉（雾

**Comment by Drelf2018** [comment]
> 诶…？太长，json库解不动？ 感觉3w不多啊，py这么拉（雾

是数据太多，接收到的数据不全导致解析不了

**Comment by Drelf2018** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/41439182/ad0e3e5c-ea17-4008-a3ad-539154eb2198)

**Comment by z0z0r4** [comment]
感觉多少可能有点关系，但摸不着头脑

`sync` 下测试不到100+请求次数就会炸，概率很高

而我复制出 url 在 httpx 库中同步请求了半天都没能出事...

都 600+ 了...依旧没事
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/d5db323c-d9e2-4e66-9d64-47de99149772)

**Comment by z0z0r4** [comment]
感觉多少可能有点关系，但摸不着头脑

`sync` 下测试不到100+请求次数就会炸，概率很高

而我复制出 url 在 httpx 库中同步请求了半天都没能出事...

都 600+ 了...依旧没事
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/d5db323c-d9e2-4e66-9d64-47de99149772)

**Comment by z0z0r4** [comment]
没头绪，暂时开摆
