### ISSUE TITLE
【漏洞】{'type' object is not subscriptable}

### ISSUE THREAD

**Issue by wwdok** [Nemo2011/bilibili-api#342]
**Python 版本：** 3.8.10

**模块版本：** 10.0.1 

**运行环境：** Windows

**模块路径：** `bilibili_api.xxxx`

**解释器：** cpython / pypi / jython

**报错信息：**

```
Traceback (most recent call last):
  File "d:/AI/PythonScripts/哔哩学习助手/bilibili_api_demo.py", line 30, in <module>
    from bilibili_api import video
  File "C:\Users\weida\AppData\Local\Programs\Python\Python38\lib\site-packages\bilibili_api\video.py", line 43, in <module>
    class Video:
  File "C:\Users\weida\AppData\Local\Programs\Python\Python38\lib\site-packages\bilibili_api\video.py", line 514, in Video
    async def get_danmakus(self, page_index: int = None, date: datetime.date = None, cid: int = None) -> list[Danmaku]:
TypeError: 'type' object is not subscriptable
```

**报错代码：**

```
import asyncio
from bilibili_api import video

async def main() -> None:
    # 实例化 Video 类
    v = video.Video(bvid="BV1uv411q7Mv")
    # 获取信息
    info = await v.get_info()
    # 打印信息
    print(info)

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

---

我刚安装好想跑个官方demo就遇到了报错。

还有，我想在另一台电脑上尝试，但这台电脑是python3.7，咱们这个库真的非python3.8不可吗，我是不想升级pyhton版本，因为这意味着所有site packages需要重装

**Comment by z0z0r4** [comment]
> 模块版本： 10.0.1
你更新试试看...？现在版本 v15 了都

**Comment by wwdok** [comment]
@z0z0r4 多谢，可以了，没想到我装的不是最新版
