### ISSUE TITLE
【提问】获取up主视频信息时显示403错误

### ISSUE THREAD

**Issue by scp23328** [Nemo2011/bilibili-api#371]
**Python 版本：** 3.1.0

**模块版本：** 15.5.1

**运行环境：** Windows

---

在运行程序获取up主视频信息及评论时弹出如下信息
File "G:\bilishiping\venv\main.py", line 72, in <module>
    sync(main())
  File "G:\bilishiping\venv\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\bilishiping\venv\main.py", line 24, in main
    v = await u.get_videos(keyword=keywords, pn=pn, ps=ps, order=order)
  File "G:\bilishiping\venv\lib\site-packages\bilibili_api\user.py", line 402, in get_videos
    return await request(
  File "G:\bilishiping\venv\lib\site-packages\bilibili_api\utils\network_httpx.py", line 530, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-403，信息：访问权限不足。
{'code': -403, 'message': '访问权限不足', 'ttl': 1}
代码如下
```
from bilibili_api import user, sync, comment,Credential
import json
from jsonsearch import JsonSearch
u = user.User(47218557)
cred= Credential(sessdata="", bili_jct="", buvid3="", dedeuserid="")
async def main():
    tid=0
    pnu=1

    pn=1
    ps=30
    keywords="推荐の本"
    word="【"
    avid=[]
    comments = []
    commkongge=[]
    message=[]
    i=0
    x=0
    com=comment.CommentResourceType.VIDEO
    order=user.VideoOrder.PUBDATE
    videoorder=comment.OrderType.LIKE
    for pn in range(1,36):
        v = await u.get_videos(keyword=keywords, pn=pn, ps=ps, order=order)
        print(v)
        json_dict_2 = json.dumps(v, indent=2, sort_keys=False, ensure_ascii=False)
        jsondata = JsonSearch(object=json_dict_2, mode='s')
        aid = jsondata.search_all_value(key='aid')
        avid=avid+aid
        print(avid)
        print(len(avid))
        print(pn)
        print(range(len(avid)))
    for i in range(len(avid)):
        print(i)
        ccom = avid[i]
        c = await comment.get_comments(ccom,com,pnu,videoorder)
        #获取视频
        json_dict_3 = json.dumps(c, indent=2, sort_keys=False, ensure_ascii=False)
        jsoncomments = JsonSearch(object=json_dict_3, mode='s')
        message = jsoncomments.search_all_value(key='message')
        messlen = len(message)
        for i in range(messlen):
            if word in message[i]:
                # 获取指定评论
                d = str(message[i])
                print(d)
                # comments.append(d)
                x = x + 1
                f=d.replace(" ","")
                if f in commkongge:
                    print("重复")
                    continue

                else:
                  commkongge.append(f)
                  comments.append(d)
            else:
                continue
    
    commdict = dict.fromkeys(comments)
    li = list(commdict.keys())
    with open('本子4.txt', 'w', encoding='utf-8') as fp:
        [fp.write(str(item) + '\n') for item in li]
    print(li)
sync(main())
```
请问我是哪里出了问题？

**Comment by Drelf2018** [comment]
更新库版本
```python
pip install bilibili-api-python --upgrade
```

**Comment by scp23328** [comment]
更新之后还是不行
试了几次后就弹这个信息
```
Traceback (most recent call last):
  File "G:\bilishiping\venv\main.py", line 72, in <module>
    sync(main())
  File "G:\bilishiping\venv\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "G:\bilishiping\venv\main.py", line 24, in main
    v = await u.get_videos(keyword=keywords, pn=pn, ps=ps, order=order)
  File "G:\bilishiping\venv\lib\site-packages\bilibili_api\user.py", line 402, in get_videos
    return await request(
  File "G:\bilishiping\venv\lib\site-packages\bilibili_api\utils\network_httpx.py", line 483, in inner
    raise ApiException("重试达到最大次数")
bilibili_api.exceptions.ApiException.ApiException: 重试达到最大次数
```

**Comment by Drelf2018** [comment]
疑似内部函数 `enc_wbi` 计算 `w_rid` 错误导致的，以下是同一时刻程序和浏览器计算出的不同 `w_rid` ：

```python
{
    'mid': 47218557,
    'ps': 30,
    'tid': 0,
    'pn': 1,
    'keyword': '推荐の本',
    'order': 'pubdate',
    'wts': 1688378234,
    'w_rid': '4abb45a824d2f08d52b73e291e7c17db'
}
```

![image](https://github.com/Nemo2011/bilibili-api/assets/41439182/8ae457e8-5d51-4684-bf85-0508ed336ee3)

@z0z0r4 怀疑是 `keyword` 中的日文导致的？

**Comment by scp23328** [comment]
去除关键词中的日语后，依然显示403

**Comment by scp23328** [comment]
这段代码至少在五月八日之前是可以包含日语运行的

**Comment by Drelf2018** [comment]
> 去除关键词中的日语后，依然显示403

关键词换成英文数字就可以正常获取，应该是库内对非ascii字符计算有误。



> 这段代码至少在五月八日之前是可以包含日语运行的

这个 `w_rid` 的改动是b站在五月二十三号上线的

**Comment by scp23328** [comment]
也就是说对up主所发布的视频进行搜索只能使用英文及数字了吗？

**Comment by Drelf2018** [comment]
破案了

>    请注意，如果参数值为中文或特殊字符，则进行 url query 编码后的字符串中参数值对应的字母必须是**大写字母** （部分库会编码为小写字母）
>
>   例如
>   ```javascript
>   {
>        foo: 'one one four',
>        bar: '五一四',
>        baz: 1919810
>   }
>   ```
>
>    应该被编码为
>
>   ```
>   bar=%E4%BA%94%E4%B8%80%E5%9B%9B&baz=1919810&foo=one%20one%20four
>   ```



> 也就是说对up主所发布的视频进行搜索只能使用英文及数字了吗？

等待新版本发布修复这个问题，现在暂时只能使用英文数字。

**Comment by scp23328** [comment]
好的，感谢大佬

**Comment by z0z0r4** [comment]
fixed
