### ISSUE TITLE
【提问】使用pyinstaller打包报错

### ISSUE THREAD

**Issue by iAilu** [Nemo2011/bilibili-api#400]
**Python 版本：** 3.9

**模块版本：** 15.5.1b0

**运行环境：** Windows

---

如题，在打包后运行报这个错误。
``` [15136] Failed to execute script 'main' due to unhandled exception!
Exception ignored in atexit callback: <function __clean at 0x0000011B0241CD30>
Traceback (most recent call last):
  File "bilibili_api\utils\network.py", line 26, in __clean
  File "asyncio\events.py", line 656, in get_event_loop
RuntimeError: There is no current event loop in thread 'MainThread'.```
不过该错误与版本无关，一直就存在。之前修改了库里的文件可以运行了，更新了版本后忘记上次如何解决的，打包成exe后无法运行了。。

**Comment by Drelf2018** [comment]
展示下源代码，感觉是因为你在异步函数内以同步形式调用了库里的函数

**Comment by iAilu** [comment]
额参考了pyinstaller打包的公告这个问题也跟着解决了。
