### ISSUE TITLE
[BUG] video_uploader API 调用错误

### ISSUE THREAD

**Issue by yes-github** [Nemo2011/bilibili-api#416]
**Python 版本：** 3.9.12

**模块版本：** 15.5.3

**运行环境：** Windows

---

上传视频的时候报错：

**TypeError: bilibili_api.utils.network_httpx.Api.update_data() argument after ** must be a mapping, not str**

```
Traceback (most recent call last):
  File "D:\xxxx\main.py", line 119, in <module>
    run("5", "3521029")
  File "D:\xxxx\main.py", line 109, in run
    sync(uploader.start())
  File "C:\ProgramData\Anaconda3\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\bilibili_api\video_uploader.py", line 456, in start
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\bilibili_api\video_uploader.py", line 448, in start
    result = await task
  File "C:\ProgramData\Anaconda3\lib\site-packages\bilibili_api\video_uploader.py", line 431, in _main
    result = await self._submit(videos, cover_url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bilibili_api\video_uploader.py", line 753, in _submit
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\bilibili_api\video_uploader.py", line 744, in _submit
    resp = await Api(**api, credential=self.credential, no_csrf=True
TypeError: bilibili_api.utils.network_httpx.Api.update_data() argument after ** must be a mapping, not str
```

**Comment by Drelf2018** [comment]
解决办法

https://github.com/Nemo2011/bilibili-api/blob/d184c038bf5a3a15871ffaa651e065ac3d3c2455/bilibili_api/video_uploader.py#L733-L747

```diff
- .update_data(**data
+ .update_data(**meta
```

**Comment by yes-github** [comment]
[完整的修复](https://github.com/yes-github/bilibili-api/compare/main...yes-github-patch-1#diff-d94567117639dea8ca3c4e667129f4894b0630f12fa3f9bb509b6d17845c6978)

**Comment by z0z0r4** [comment]
> [完整的修复](https://github.com/yes-github/bilibili-api/compare/main...yes-github-patch-1#diff-d94567117639dea8ca3c4e667129f4894b0630f12fa3f9bb509b6d17845c6978)

需要 json_body？

**Comment by HowHsu** [comment]
在Mac平台，bilibili-api-python version 16.1.0也遇到了这个问题，目前进展如何了

**Comment by z0z0r4** [comment]
> 在Mac平台，bilibili-api-python version 16.1.0也遇到了这个问题，目前进展如何了

提供下报错

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/issues/504
