### ISSUE TITLE
[漏洞] user.get_user_info调用报错

### ISSUE THREAD

**Issue by blyc** [Nemo2011/bilibili-api#450]
**Python 版本：** 3.9.16

**模块版本：** 1.15.5~dev

**运行环境：** Windows

**模块路径：** `bilibili_api.user`

**报错信息：**

```
[Request][2023-08-24 15:57:18,332] Api(url='https://api.bilibili.com/x/space/wbi/acc/info', method='GET', comment='用户基本信息', wbi=True, verify=False, no_csrf=False, json_body=False, ignore_code=False, data={}, params={'mid': 97164600}, files={}, headers={}, credential=<bilibili_api3.utils.credential.Credential object at 0x00000235BBF6FD90>)
2023-08-24 15:57:18.332 |INFO    | bilibili_api3.utils.network_httpx.request: 244 | - Api(url='https://api.bilibili.com/x/space/wbi/acc/info', method='GET', comment='用户基本信息', wbi=True, verify=False, no_csrf=False, json_body=False, ignore_code=False, data={}, params={'mid': 97164600}, files={}, headers={}, credential=<bilibili_api3.utils.credential.Credential object at 0x00000235BBF6FD90>)
[Request][2023-08-24 15:57:18,333] Api(url='https://api.bilibili.com/x/web-interface/nav', method='GET', comment='如果 code = 0 则 cookies 有效', wbi=False, verify=True, no_csrf=False, json_body=False, ignore_code=True, data={}, params={}, files={}, headers={}, credential=<bilibili_api3.utils.credential.Credential object at 0x00000235BC008EE0>)
2023-08-24 15:57:18.333 |INFO    | bilibili_api3.utils.network_httpx.request: 244 | - Api(url='https://api.bilibili.com/x/web-interface/nav', method='GET', comment='如果 code = 0 则 cookies 有效', wbi=False, verify=True, no_csrf=False, json_body=False, ignore_code=True, data={}, params={}, files={}, headers={}, credential=<bilibili_api3.utils.credential.Credential object at 0x00000235BC008EE0>)
Traceback (most recent call last):
  File "C:\Users\Lyc\Documents\PycharmProjects\danmaku\test.py", line 32, in <module>
    res = sync(User(uid=97164600).get_user_info())
  File "C:\Users\Lyc\Documents\PycharmProjects\danmaku\bilibili_api3\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Users\Lyc\.conda\envs\danmaku\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Lyc\Documents\PycharmProjects\danmaku\bilibili_api3\user.py", line 231, in get_user_info
    return await Api(**API["info"]["info"], credential=self.credential).update_params(**params).result
  File "C:\Users\Lyc\Documents\PycharmProjects\danmaku\bilibili_api3\utils\network_httpx.py", line 159, in result
    self.__result = await self.request()
  File "C:\Users\Lyc\Documents\PycharmProjects\danmaku\bilibili_api3\utils\network_httpx.py", line 61, in inner
    return await func(*args, **kwargs)
  File "C:\Users\Lyc\Documents\PycharmProjects\danmaku\bilibili_api3\utils\network_httpx.py", line 310, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api3.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-401，信息：非法访问。
{'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level2'], 'risk_level': 1, 'grisk_id': '3c0d76bd1c776924213788780364e70d', 'decision_ctx': {'buvid': '931081E9D-AE3E-9F5F-9109F-6E1521591018836102infoc', 'decision_type': '4', 'ip': '222.66.117.26', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'anti_crawler', 'ua': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37', 'v_voucher': 'voucher_efbe5d63-82b6-43b7-9b81-bfe24ee45f58'}}}}

```

**报错代码：**

```
if __name__ == '__main__':
    settings.request_log = True
    res = sync(User(uid=97164600).get_user_info())
    print(res)
```

---

只测试了回退到1.15.1正常，后续版本是同样的报错

**Comment by z0z0r4** [comment]
![image](https://github.com/Nemo2011/bilibili-api/assets/78744121/0eb51f17-b741-472d-9cd1-4dc83f853373)

大概是修好了，UA过期（虽然不知道为什么B站居然要求UA...

建议尝试下自己修改 [`055d237` (#451)](https://github.com/Nemo2011/bilibili-api/pull/451/commits/055d2377dfebcd31a1e5a248cf7b8a26bccd5e88#diff-2a325030cfc80c35d01c092e86d9f489bc3e669a4340e254ca126274d9a33694L35) 试试看，等确认没有问题才能发 issue

**Comment by blyc** [comment]
> 



> ![image](https://user-images.githubusercontent.com/78744121/262965733-0eb51f17-b741-472d-9cd1-4dc83f853373.png)
> 
> 大概是修好了，UA过期（虽然不知道为什么B站居然要求UA...
> 
> 建议尝试下自己修改 [`055d237` (#451)](https://github.com/Nemo2011/bilibili-api/pull/451/commits/055d2377dfebcd31a1e5a248cf7b8a26bccd5e88#diff-2a325030cfc80c35d01c092e86d9f489bc3e669a4340e254ca126274d9a33694L35) 试试看，等确认没有问题才能发 issue

直接拉了dev测试的，看了 #435 就多测了几个user接口，不过也没做到全测试一遍 ~看到回复才意识到已经有issues了~

个人测试几个接口都没有问题
_最后两个接口报错和本次无关，只是接口要登录似乎没有和其他接口一样的`credential.raise_for_no_sessdata()`_
![image](https://github.com/Nemo2011/bilibili-api/assets/34291620/4e0aeb8f-0e66-4e1f-9420-eb1357811c61)

**Comment by z0z0r4** [comment]
> > 
> 
> > ![image](https://user-images.githubusercontent.com/78744121/262965733-0eb51f17-b741-472d-9cd1-4dc83f853373.png)
> > 大概是修好了，UA过期（虽然不知道为什么B站居然要求UA...
> > 建议尝试下自己修改 [`055d237` (#451)](https://github.com/Nemo2011/bilibili-api/pull/451/commits/055d2377dfebcd31a1e5a248cf7b8a26bccd5e88#diff-2a325030cfc80c35d01c092e86d9f489bc3e669a4340e254ca126274d9a33694L35) 试试看，等确认没有问题才能发 issue
> 
> 直接拉了dev测试的，看了 #435 就多测了几个user接口，不过也没做到全测试一遍 ~看到回复才意识到已经有issues了~
> 
> 个人测试几个接口都没有问题 _最后两个接口报错和本次无关，只是接口要登录似乎没有和其他接口一样的`credential.raise_for_no_sessdata()`_ ![image](https://user-images.githubusercontent.com/34291620/262981735-4e0aeb8f-0e66-4e1f-9420-eb1357811c61.png)

那个issue只是我等着收集反爬数据的，引用下而已

不是 -401 就行了，finished
