### ISSUE TITLE
[漏洞] Credential的.refresh()抛出“获取刷新 Cookies 的 csrf 失败。”

### ISSUE THREAD

**Issue by TZFC** [Nemo2011/bilibili-api#568]
**Python 版本：** 3.11.6

**模块版本：** 16.1.1

**运行环境：** Linux

**模块路径：** `bilibili_api.xxxx`

**解释器：** cpython / pypi / jython

**报错信息：**

注：getCredential是用我的登录信息返回一个Credential对象；bili_jct简单打码
```
>>> from CredentialGetter import getCredential
>>> from bilibili_api import sync
>>> c = getCredential("tzfc")
>>> print(c.bili_jct)
c8833****e6cfc281b7512fbe145e15a
>>> print(sync(c.check_refresh()))
True
>>> sync(c.refresh())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/BiliLiveManager/py311/lib/python3.11/site-packages/bilibili_api/utils/sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/BiliLiveManager/py311/lib/python3.11/site-packages/bilibili_api/credential.py", line 51, in refresh
    new_cred: Credential = await refresh_cookies(self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/BiliLiveManager/py311/lib/python3.11/site-packages/bilibili_api/credential.py", line 144, in refresh_cookies
    refresh_csrf = await get_refresh_csrf(credential)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/BiliLiveManager/py311/lib/python3.11/site-packages/bilibili_api/credential.py", line 128, in get_refresh_csrf
    raise Exception("获取刷新 Cookies 的 csrf 失败。")
Exception: 获取刷新 Cookies 的 csrf 失败。
>>> c.bili_jct
'c8833****e6cfc281b7512fbe145e15a'
```

**报错代码：**

```
获取刷新 Cookies 的 csrf 失败。
```

---

按照[doc](https://nemo2011.github.io/bilibili-api/#/refresh_cookies)里的方式尝试刷新credentials。`sessdata, bili_jct, buvid3, ac_time_value` 四项全部提供。然而刷新不了，get_refresh_csrf报错“获取刷新 Cookies 的 csrf 失败。”

**Comment by TZFC** [comment]
使用 dev branch测试刷新没有问题。

**Comment by 17yjgao** [comment]
dev branch刷新遇到Exception: correspondPath 过期或错误, 是b站改correspondPath 算法了吗？
