### ISSUE TITLE
直播间连接失败

### ISSUE THREAD

**Issue by Pasumao** [Nemo2011/bilibili-api#584]
**Python 版本：** 3.10.13

模块版本：16.1.1

**运行环境：** Windows
使用的是文档里的[示例：直播间礼物统计](https://nemo2011.github.io/bilibili-api/#/examples/live?id=%e7%a4%ba%e4%be%8b%ef%bc%9a%e7%9b%b4%e6%92%ad%e9%97%b4%e7%a4%bc%e7%89%a9%e7%bb%9f%e8%ae%a1)
连接直播间报错
=============================================
```
[21452505][2023-12-04 20:21:10,987][INFO] 准备连接直播间 21452505
Traceback (most recent call last):
  File "e:\vscode\bilibili_gift_to_kbd\bilibili.py", line 50, in <module>
    sync(room.connect())  # 连接直播间
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Users\18303\.conda\envs\bili\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\live.py", line 873, in connect
    await self.__main()
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\live.py", line 910, in __main
    conf = await room.get_chat_conf()
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\live.py", line 208, in get_chat_conf
    await Api(**api, credential=self.credential).update_params(**params).result
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\utils\network.py", line 170, in result
    self.__result = await self.request()
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\utils\network.py", line 70, in inner
    return await func(*args, **kwargs)
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\utils\network.py", line 252, in request
    self.credential.raise_for_no_sessdata()
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\utils\credential.py", line 117, in raise_for_no_sessdata
    raise CredentialNoSessdataException()
bilibili_api.exceptions.CredentialNoSessdataException.CredentialNoSessdataException: Credential 类未提供 sessdata 或者为空。
```
=============================================
但是我根据文档去刷新credential类的sessdata，也是刷新的示例代码
False
```
Traceback (most recent call last):
  File "e:\vscode\bilibili_gift_to_kbd\bilibili.py", line 58, in <module>
    sync(credential.refresh())
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "C:\Users\18303\.conda\envs\bili\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\credential.py", line 51, in refresh
    new_cred: Credential = await refresh_cookies(self)
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\credential.py", line 144, in refresh_cookies
    refresh_csrf = await get_refresh_csrf(credential)
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\credential.py", line 128, in get_refresh_csrf
    raise Exception("获取刷新 Cookies 的 csrf 失败。")
Exception: 获取刷新 Cookies 的 csrf 失败。
```
=============================================

**Comment by NekoWings** [comment]
试试`live.LiveDanmaku(xxxx, credential=credential)`
我之前也是按照文档`live.LiveDanmaku(xxxx, credential)`，看上去并没有给credential赋上值

**Comment by z0z0r4** [comment]
```python
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from bilibili_api import live, sync


class Gift(TypedDict):
    '''用户赠送礼物列表
    username: 用户名
    last_gift_time: 最后一次赠送礼物时时间戳
    gift_list: 赠送的礼物字典，格式 礼物名: 数量'''
    username: str
    last_gift_time: int
    gift_list: Dict[str, int]

user_list: Dict[int, Gift] = dict()
room = live.LiveDanmaku(21452505)
sched = AsyncIOScheduler(timezone="Asia/Shanghai")  # 定时任务框架

@room.on('SEND_GIFT')
async def on_gift(event):
    '记录礼物'
    info = event['data']['data']
    uid = info['uid']
    user = user_list.get(uid)
    if user:
        # 如果用户列表中有该用户 则更新他的礼物字典以及礼物时间戳
        num = user['gift_list'].get(info['giftName'], 0)
        user['gift_list'][info['giftName']] = num + info['num']
        user['last_gift_time'] = int(time.time())
    else:
        # 不存在则以现在时间及礼物新建 Gift 对象
        user_list[uid] = Gift(
            username=info['uname'],
            last_gift_time=int(time.time()),
            gift_list={info['giftName']: info['num']}
        )
        # 开启一个监控
        sched.add_job(check, 'interval', seconds=1, args=[uid], id=str(uid))

async def check(uid: int):
    '判断是否超过阈值并输出'
    user = user_list.get(uid)
    if user:
        if int(time.time()) - user.get('last_gift_time', 0) > 5:  # 此处的 5 即需求中的 n 表示秒数
            sched.remove_job(str(uid))  # 移除该监控任务
            print(user_list.pop(uid))  # 将该用户从列表中弹出并打印

if __name__ == '__main__':
    sched.start()  # 启动定时任务
    sync(room.connect())  # 连接直播间
```

我愣是没找到哪里 `credential`...

https://nemo2011.github.io/bilibili-api/#/examples/live?id=%e7%a4%ba%e4%be%8b%ef%bc%9a%e7%9b%b4%e6%92%ad%e9%97%b4%e8%b5%a0%e9%80%81%e9%87%91%e7%93%9c%e5%ad%90%e7%a4%bc%e7%89%a9 倒是有
