### ISSUE TITLE
[建议] 登录 412 风控

### ISSUE THREAD

**Issue by Ikaros-521** [Nemo2011/bilibili-api#587]
修改 login.py
```
def update_qrcode_data() -> dict:
    api = API["qrcode"]["get_qrcode_and_token"]
    # qrcode_data = httpx.get(api["url"], follow_redirects=True).json()["data"]
    try:
        response = httpx.get(api["url"], follow_redirects=True)
        if response.status_code == 200:
            qrcode_data = response.json()["data"]
        else:
            print(f"Error: HTTP {response.status_code} - {response.text}")
            # Handle error or retry as appropriate
    except json.decoder.JSONDecodeError as e:
        print(f"JSON decoding failed: {e}")
        # Handle the JSON decoding error
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
```

```
Error: HTTP 412 - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="zh-cn">

<head>
    <meta http-equiv="Access-Control-Allow-Origin" content="*" />
    <meta http-equiv="Page-Enter" content="blendTrans(Duration=0.5)">
    <meta http-equiv="Page-Exit" content="blendTrans(Duration=0.5)">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="spm_prefix" content="333.937">
    <title>出错啦! - bilibili.com</title>
    <link rel="shortcut icon" href="//static.hdslb.com/images/favicon.ico">
    <script type="text/javascript" src="//s1.hdslb.com/bfs/static/jinkela/long/js/jquery/jquery1.7.2.min.js"></script>

</head>

<body>
    <div class="error-container">
        <div class="txt-item err-code">错误号:412</div>
        <div class="txt-item err-text">由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝。</div>
        <div class="txt-item">The request was rejected because of the bilibili security control policy.</div>
        <div class="txt-item datetime_now"></div>
        <div class="txt-item user_url"></div>
        <div class="txt-item user_ip"></div>
        <div class="txt-item user_id"></div>
        <div class="check-input">
            <div class="title"></div>
            <div class="box-pic"></div>
            <div class="box"></div>
            <div class="state"></div>
        </div>
    </div>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/sha256.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/js.cookie.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/412.js"></script>
</body>
</html>
2023-12-07 23:20:46,150 - D:\GitHub_pro\AI-Vtuber\bilibili.py[line:422] - ERROR: Traceback (most recent call last):
  File "D:\GitHub_pro\AI-Vtuber\bilibili.py", line 406, in start_server
    credential = login.login_with_qrcode()
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\bilibili_api\login.py", line 129, in login_with_qrcode
    qrcode_data = update_qrcode_data()
  File "D:\GitHub_pro\AI-Vtuber\venv\lib\site-packages\bilibili_api\login.py", line 103, in update_qrcode_data
    return qrcode_data
UnboundLocalError: local variable 'qrcode_data' referenced before assignment
```

**Comment by blyc** [comment]
https://github.com/Nemo2011/bilibili-api/issues/588

**Comment by Ikaros-521** [comment]
> https://github.com/Nemo2011/bilibili-api/issues/588

感谢，这应该直接合到新版去😋

**Comment by z0z0r4** [comment]
412 不是频率过高吗？你这俩went

**Comment by Ikaros-521** [comment]
> 412 不是频率过高吗？你这俩问题

一天来回启动个好几次bushi，之前掉线不一直重连失败。
我这ip之前也经常爬b站😋

**Comment by blyc** [comment]
> 412 不是频率过高吗？你这俩问题

`get_qrcode_and_token`这个接口之前不加headers响应的直接就是412，反而和频率过高关系不大的样子
阿b的响应码真的迷

**Comment by z0z0r4** [comment]
`pip install bilibili-api-dev --upgrade`

**Comment by Ikaros-521** [comment]
> `pip install bilibili-api-dev --upgrade`

亲测有用
