### ISSUE TITLE
[漏洞] 短信登录时校验网页空白 控制台报错

### ISSUE THREAD

**Issue by iAilu** [Nemo2011/bilibili-api#590]
**Python 版本：** 3.9

**模块版本：** 16.1.1

**运行环境：** Windows

**报错信息：**

```
请打开 http://127.0.0.1:51422/ 进行验证。
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 51423)
Traceback (most recent call last):
  File "C:\Users\u\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\u\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\u\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\u\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\u\AppData\Local\Programs\Python\Python39\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\u\AppData\Local\Programs\Python\Python39\lib\http\server.py", line 415, in handle_one_request
    method()
  File "D:\Project\Python\Yue\venv\lib\site-packages\bilibili_api\utils\captcha.py", line 152, in do_GET
    self.wfile.write(self.urlhandler(self.path, content_type).encode("utf-8"))  # type: ignore
  File "D:\Project\Python\Yue\venv\lib\site-packages\bilibili_api\utils\captcha.py", line 56, in _geetest_urlhandler
    gt = json_data["data"]["geetest"]["gt"]
KeyError: 'data'
```

在使用短信验证登录时，运行弹出的验证页面空白，控制台报上面错误。
登录代码如下
``` python
print("正在登陆...")
phone = "13333333333"
print("正在发送验证码")
send_sms(PhoneNumber(phone, country="+86"))  # 默认设置地区为中国大陆
code = input("请输入验证码：")

c = login_with_sms(PhoneNumber(phone, country="+86"), code)
if isinstance(c, Check):
    # 还需验证
    print("需要进行验证。请考虑使用二维码登录")
    exit(1)
else:
    self.credential = c
    self.credential.buvid3 = str(uuid.uuid1())
    print("登录成功")
```

**Comment by z0z0r4** [comment]
不建议短信说实话
