### ISSUE TITLE
[提问] 获取用户关系失败

### ISSUE THREAD

**Issue by xiaoxiaohaoa** [Nemo2011/bilibili-api#601]
**Python 版本：** 3.11.7

**模块版本：** main

**运行环境：** Windows

---
获取”与私信发送者的关系“时报错
ApiException.ApiException: 重试达到最大次数
```
Task exception was never retrieved
future: <Task finished name='Task-605' coro=<reply() done, defined at ..\test-api.py:26> exception=ApiException('重试达到最大次数')>
Traceback (most recent call last):
  File "..\test-api.py", line 31, in reply
    rela = await talker.get_relation(uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\bilibili_api\user.py", line 761, in get_relation
    await Api(**api, credential=self.credential).update_params(**params).result
  File "..\bilibili_api\utils\network.py", line 170, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "..\bilibili_api\utils\network.py", line 82, in inner
    raise ApiException("重试达到最大次数")
bilibili_api.exceptions.ApiException.ApiException: 重试达到最大次数
```
本意是想实现根据私信关键词自动回复的功能，附带检测用户的关注状态的参数。大体架构完成后这句话一直可以正常运行，但在某次编辑后突然报错。当次编辑是接近末尾的段落，但报错的位置靠前，很疑惑；由于本人没有编程经验，manual里也没有找到有关”重试达到最大次数“的说明，不知道该怎么解决，希望能得到指点。

完整代码如下：
```
import asyncio
from bilibili_api import Credential, sync, user
from bilibili_api.session import Session, Event
from bilibili_api.user import User, RelationType


#登录凭据，记得改成自己的
SESSDATA = "※"
BILI_JCT = "※"
BUVID3 = "※"

credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)
session = Session(credential)

list1 = [] #用于记录收到私信的粉丝的uid
list2 = [] #用于记录关注时间，作为判定取关并重新关注操作的凭据

with open('list1.txt',"a+") as f: #读取已记录列表，该列表存储在本地，位置为指令执行时所处的目录
    for line in f:
        list1.append(line.strip()) 

with open('list2.txt',"a+") as f: #同上
    for line in f:
        list2.append(line.strip()) 

@session.on(Event.TEXT) #轮询，检测收到文字私信时触发
async def reply(event: Event):

    uid = event.sender_uid #查询发信者的uid
    talker = User(uid, credential)
    rela = await talker.get_relation(uid)

                      ^此处报错^

    follow = rela['be_relation']['attribute'] #查询关注关系，此处描述的是对方对你的关注状态：0=未关注，2=已关注，6=互关，128=黑名单
    mtime = rela['be_relation']['mtime'] #关注时间，以时间戳的形式记录，未关注时为0，取关后重新关注会刷新，以此为凭据进行拉黑；需注意关系变为互相关注时也会刷新，后文单独拎出来讨论
    fid = str(uid) #转换为字符串
    ftime = fid + str(mtime) #同上

    print(list1) #这一句跟末尾的一句呼应，用来在执行脚本时检查list是否正常运作：每个uid都被视为列表中的独立元素；开始自动轮询后就没有实际效果了，测试顺利的话可以删除
    print(list2) #同上

    if follow > 0 and follow < 128: #筛选：已关注用户

        if fid not in list1: #筛选：未通过关键词获取过回复的粉丝

            if event.content == "/结束": #用于结束轮询的口令，触发后你将不再自动回复私信，最好设置成别人不会随便说出来的语句
                session.close()

            elif event.content == "关键词1": #正确的关键词，标志着对方成功获取回复；触发时发信人的uid和关注时间会随之被记录
                await session.reply(event, "回复1") #正确关键词对应的回复
                
                list1.extend([fid]) #记录发信粉丝的uid
                with open("list1.txt","a+") as f: 
                    f.write(fid + "\n")
                
                list2.extend([ftime]) #记录发信粉丝的uid和关注时间
                with open("list2.txt","a+") as f: 
                    f.write(ftime + "\n")

            elif event.content == "关键词2": #正确的关键词2，以此类推，需要多少关键词就把“elif”开头的这一整段复制粘贴多少遍（记得修改好对应的文本）
                await session.reply(event, "回复2")

                list1.extend([fid])
                with open("list1.txt","a+") as f:
                    f.write(fid + "\n")

                list2.extend([ftime]) 
                with open("list2.txt","a+") as f: 
                    f.write(ftime + "\n")

            else:
                await session.reply(event, "关键词错误，请重试") #关键词错误，无事发生；如果对方是第一次向你发私信，可以在收到你的自动回复后继续给你发送私信；如果不想这样做，把这句话连同“else”一起删掉

        else: #曾通过关键词获取过回复的粉丝

            if ftime in list2 or follow == 6: #对方两次私信的关注时间一致（或关系为互相关注），说明对方自上次获取回复后没有取消关注过（或对方是你的好友），此时执行正常流程，跟上文一致，但不重复记录

                if event.content == "/结束": 
                    session.close()

                elif event.content == "关键词1": 
                    await session.reply(event, "回复1") 

                elif event.content == "关键词2": 
                    await session.reply(event, "回复2")

                else:
                    await session.reply(event, "关键词错误，请重试") 
            
            else: #对方两次私信的关注时间不一致且不是你的互关好友，说明对方自上次获取回复后曾取消关注
                await session.reply(event, "自动回复已失效，原因：曾在拿到资源后取消关注") 

                #如果想要拉黑，复制粘贴这一句：【await talker.modify_relation(relation=RelationType.BLOCK)】


    print(list1) #这一句跟开头的一句呼应，用来在执行脚本时检查list是否正常运作：每个uid都被视为列表中的独立元素；开始自动轮询后就没有实际效果了，测试顺利的话可以删除
    print(list2) #同上
sync(session.start())

```

**Comment by z0z0r4** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/issues/910

**Comment by xiaoxiaohaoa** [comment]
> [SocialSisterYi/bilibili-API-collect#910](https://github.com/SocialSisterYi/bilibili-API-collect/issues/910)

感谢！看样子BAC那边暂时还没有跟进接口信息？感觉要等一会儿了……
我还挺想尽快把这一段写出来的，不知道想要获取用户关系属性还有没有别的办法？

**Comment by z0z0r4** [comment]
我直接修了吧，没调用 wbi: true 而已

**Comment by z0z0r4** [comment]
https://github.com/Nemo2011/bilibili-api/commit/7bc108647ed0251921337b8a85cb6b1704141c73

**Comment by xiaoxiaohaoa** [comment]
> [7bc1086](https://github.com/Nemo2011/bilibili-api/commit/7bc108647ed0251921337b8a85cb6b1704141c73)
> 
> 你试试看能不能用，直接 dev 分支源码安装

抱歉，试着用pip下载分支结果报错了……这里应该怎么安装？

**Comment by z0z0r4** [comment]
`pip install git+https://github.com/Nemo2011/bilibili-api.git@dev`

**Comment by xiaoxiaohaoa** [comment]
> > > [7bc1086](https://github.com/Nemo2011/bilibili-api/commit/7bc108647ed0251921337b8a85cb6b1704141c73)
> > > 你试试看能不能用，直接 dev 分支源码安装
> > 
> > 
> > 抱歉，试着用pip下载分支结果报错了……这里应该怎么安装？
> 
> 啥报错

```
Looking in indexes: https://pypi.org/simple/admin-logs/
Collecting git+https://github.com/Nemo2011/bilibili-api.git@dev
  Cloning https://github.com/Nemo2011/bilibili-api.git (to revision dev) to c:\..\local\temp\pip-req-build-lsgrib6o
  Running command git clone --filter=blob:none --quiet https://github.com/Nemo2011/bilibili-api.git 'C:\Users\..\AppData\Local\Temp\pip-req-build-lsgrib6o'
  Running command git checkout -b dev --track origin/dev
  branch 'dev' set up to track 'origin/dev'.
  Switched to a new branch 'dev'
  Resolved https://github.com/Nemo2011/bilibili-api.git to commit 7bc108647ed0251921337b8a85cb6b1704141c73
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://pypi.org/simple/admin-logs/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
```
仍然报错……我实在不太懂这些基础知识……
但是我直接在`..\AppData\Local\Programs\Python\Python311\Lib\site-packages\bilibili_api\data\api\user.json`里的"relation"段落添加了`"wbi": true,`，现在可以正常运行了。
非常感谢！帮大忙了！
