### ISSUE TITLE
[漏洞] 有dolby音效时获取最好的流时出错

### ISSUE THREAD

**Issue by nooblong** [Nemo2011/bilibili-api#613]
**Python 版本：** 3

**模块版本：** main/dev

**运行环境：** MacOS

**模块路径：** `bilibili_api.video.detect_best_streams()`

**解释器：** cpython

**报错信息：**

```python
Traceback (most recent call last):
  File "bilibili-api/server.py", line 181, in <module>
    sync(test())
  File "bilibili-api/bilibili_api/utils/sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "bilibili-api/server.py", line 178, in test
    streams = detecter.detect_best_streams()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "bilibili-api/bilibili_api/video.py", line 2421, in detect_best_streams
    data = self.detect(
           ^^^^^^^^^^^^
  File "bilibili-api/bilibili_api/video.py", line 2348, in detect
    dolby_stream_url = dolby_data["audio"]["baseUrl"]
                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**报错代码：**

```python
            if dolby_data and (not no_dolby_audio):
                if dolby_data["audio"]:
                    dolby_stream_url = dolby_data["audio"]["baseUrl"]
                    dolby_stream_quality = AudioQuality(dolby_data["audio"]["id"])
                    dolby_stream = AudioStreamDownloadURL(
                        url=dolby_stream_url, audio_quality=dolby_stream_quality
                    )
                    streams.append(dolby_stream)
            return streams
```

---

使用这个bvid：BV1gw411W7aU 时，dolby音效为数组
<img width="1275" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/19368870/384c071c-e517-4c48-afc6-1aa7fa40a5e5">

**Comment by z0z0r4** [comment]
了解，元旦处理

**Comment by z0z0r4** [comment]
可以试试看 dev 分支

**Comment by nooblong** [comment]
> 可以试试看 dev 分支

可以了
