### ISSUE TITLE
[提问] 登录二维码获取失败，显示被风控拒绝

### ISSUE THREAD

**Issue by Pasumao** [Nemo2011/bilibili-api#630]
**Python 版本：** 3.10.13

**模块版本：** 16.1.1
**运行环境：** Windows 

```
from bilibili_api import login, user, sync
print("请登录：")
credential = login.login_with_qrcode_term() # 在终端扫描二维码登录
# credential = login.login_with_qrcode() # 使用窗口显示二维码登录
try:
    credential.raise_for_no_bili_jct() # 判断是否成功
    credential.raise_for_no_sessdata() # 判断是否成功
except:
    print("登陆失败。。。")
    exit()
print("欢迎，", sync(user.get_self_info(credential))['name'], "!")
```
这是文档里的登录，[示例: 终端简易二维码登录脚本](https://nemo2011.github.io/bilibili-api/#/examples/login?id=%e7%a4%ba%e4%be%8b-%e7%bb%88%e7%ab%af%e7%ae%80%e6%98%93%e4%ba%8c%e7%bb%b4%e7%a0%81%e7%99%bb%e5%bd%95%e8%84%9a%e6%9c%ac)

```
请登录：
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="zh-cn">

<head>
    <meta http-equiv="Access-Control-Allow-Origin" content="*" />
    <meta http-equiv="Page-Enter" content="blendTrans(Duration=0.5)">
    <meta http-equiv="Page-Exit" content="blendTrans(Duration=0.5)">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="spm_prefix" content="333.937">
    <title>出错啦! - bilibili.com</title>
    <link rel="shortcut icon" href="//static.hdslb.com/images/favicon.ico">
    <script type="text/javascript" src="//s1.hdslb.com/bfs/static/jinkela/long/js/jquery/jquery1.7.2.min.js"></script>

</head>

<body>
    <div class="error-container">
        <div class="txt-item err-code">错误号:412</div>
        <div class="txt-item err-text">由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝。</div>
        <div class="txt-item">The request was rejected because of the bilibili security control policy.</div>
        <div class="txt-item datetime_now"></div>
        <div class="txt-item user_url"></div>
        <div class="txt-item user_ip"></div>
        <div class="txt-item user_id"></div>
        <div class="check-input">
            <div class="title"></div>
            <div class="box-pic"></div>
            <div class="box"></div>
            <div class="state"></div>
        </div>
    </div>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/sha256.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/js.cookie.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="//security.bilibili.com/static/js/412.js"></script>
</body>
</html>
Traceback (most recent call last):
  File "e:\vscode\bilibili_gift_to_kbd\test2.py", line 3, in <module>
    credential = login.login_with_qrcode_term() # 在终端扫描二维码登录
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\login.py", line 178, in login_with_qrcode_term
    qrcode_data = update_qrcode_data()
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\bilibili_api\login.py", line 91, in update_qrcode_data
    qrcode_data=qrcode_data1.json()["data"]
  File "C:\Users\18303\.conda\envs\bili\lib\site-packages\httpx\_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "C:\Users\18303\.conda\envs\bili\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18303\.conda\envs\bili\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\18303\.conda\envs\bili\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
这边我把get到的print出来了

**Comment by blyc** [comment]
尝试用dev版本再次测试
https://github.com/Nemo2011/bilibili-api/issues/588#issuecomment-1854024521
