### ISSUE TITLE
[提问] 为什么有的视频获取下载链接失败

### ISSUE THREAD

**Issue by dsgler** [Nemo2011/bilibili-api#673]
**Python 版本：** 3.8.10

**模块版本：** x.y.z

**运行环境：** Linux 

---
get_download_url时，返回
{'code': -400, 'message': '请求错误', 'ttl': 1}
有的视频成功，有的视频失败，不知道为什么

**Comment by dsgler** [comment]
比如BV1st421W7qJ
这个就会失败
BV14V411X71h
这个就成功了

**Comment by marcus4346** [comment]
我的做法（代码修改了私有属性，不规范，只是表达一下意思）：

    video = Video(bvid, credential=credential)
    
    # ****** START ******
    aid = video.get_aid()
    if aid < 0:
        video._Video__aid = aid + 2 ** 31
    # ******  END  ******

**Comment by z0z0r4** [comment]
> 比如BV1st421W7qJ 这个就会失败 BV14V411X71h 这个就成功了

看楼上我猜有可能是 aid 算法改了，你可以试试用 dev 分支的应该就过了

**Comment by dsgler** [comment]
> > 比如BV1st421W7qJ 这个就会失败 BV14V411X71h 这个就成功了

好像不是这个问题
Traceback (most recent call last):
  File "/home/dsgler/home/bili_favo/main.py", line 161, in <module>
    sync(main(media_id))
  File "/home/dsgler/.local/lib/python3.8/site-packages/bilibili_api/utils/sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dsgler/home/bili_favo/main.py", line 149, in main
    await download_by_bv(tasks[i])
  File "/home/dsgler/home/bili_favo/main.py", line 74, in download_by_bv
    download_url_data = await v.get_download_url(0)
  File "/home/dsgler/.local/lib/python3.8/site-packages/bilibili_api/video.py", line 448, in get_download_url
    await Api(**api, credential=self.credential).update_params(**params).result
  File "/home/dsgler/.local/lib/python3.8/site-packages/bilibili_api/utils/network.py", line 170, in result
    self.__result = await self.request()
  File "/home/dsgler/.local/lib/python3.8/site-packages/bilibili_api/utils/network.py", line 70, in inner
    return await func(*args, **kwargs)
  File "/home/dsgler/.local/lib/python3.8/site-packages/bilibili_api/utils/network.py", line 332, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-400，信息：请求错误。
{'code': -400, 'message': '请求错误', 'ttl': 1}
报错如上

**Comment by dsgler** [comment]
库已更新，出问题视频为BV1st421W7qJ（好像新一点的视频都有问题，应该是b站改api了）

**Comment by Nemo2011** [comment]
本地测试 `16.2.0` 此视频无问题。

**Comment by z0z0r4** [comment]
> 库已更新，出问题视频为BV1st421W7qJ（好像新一点的视频都有问题，应该是b站改api了）

就是 aid 炸了吧，你试试看 16.2.0

**Comment by dsgler** [comment]
···
bv='BV1st421W7qJ'
import asyncio
from bilibili_api import video, Credential, HEADERS, sync, favorite_list
import httpx
import json
from tqdm.asyncio import tqdm_asyncio
import re

v=video.Video(bv)
info=sync(v.get_info())
url=sync(v.get_download_url(0))
print(url)
···
就这段代码，这个bv有问题，报错和上面一样，是使用bilibili-api-dev
我在服务器上也试了一下，一样报错

**Comment by dsgler** [comment]
> 本地测试 `16.2.0` 此视频无问题。

是有什么要注意的地方吗

**Comment by Nemo2011** [comment]
我这里和你跑一样代码也没问题，实在不行全贴出来

**Comment by Nemo2011** [comment]
不是用 `bilibili-api-dev`，一般提到 `dev` 指的是这个仓库的 `dev` 分支。

**Comment by Nemo2011** [comment]
再说 `bilibili-api-dev` 不会放 `16.2.0`，**只放预览版**

**Comment by dsgler** [comment]
> 再说 `bilibili-api-dev` 不会放 `16.2.0`，**只放预览版**

ok了，多谢
