### ISSUE TITLE
[提问] search.search报错 certificate verify failed

### ISSUE THREAD

**Issue by Nickszy** [Nemo2011/bilibili-api#678]
**Python 版本：** 3.11.4

**模块版本：** 16.2.0

**运行环境：** MacOS

---

调用search.search,反馈
```
"name": "ClientConnectorCertificateError",
	"message": "Cannot connect to host api.bilibili.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]",
```

<img width="1101" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/29924966/4cc81cba-b3dc-451f-ab03-71b266f838ec">

尝试修改search.search函数，增加`credential`，报错与上面一致；

```
async def search(keyword: str, page: int = 1,credential = None) -> dict:
    """
    只指定关键字在 web 进行搜索，返回未经处理的字典

    Args:
        keyword (str): 搜索关键词

        page    (int): 页码. Defaults to 1.

    Returns:
        dict: 调用 API 返回的结果
    """
    api = API["search"]["web_search"]
    params = {"keyword": keyword, "page": page}
    return await Api(**api,credential=credential).update_params(**params).result

```

**Comment by TimG233** [comment]
这和加不加credential还有整个库应该没关系吧... certificate过期了就会出类似的这种错误
我自己试了下`search.search`没问题，16.2.0的

**Comment by Nemo2011** [comment]
这种情况下个人建议自行尝试不同的 `aiohttp.ClientSession` 参数，每次调用模块的时候设置这个 `ClientSession` 给模块使用，直到可以正常访问。

具体就是 `set_aiohttp_session(aiohttp.ClientSession(你调整后可以用的参数))`，个人觉得可以先尝试设置 `connector=TCPConnector(ssl=False)` (关掉 ssl)，这样子 `ssl` 也不会有问题，至于 b 站拦不拦你，我就不知道了。

**Comment by Nemo2011** [comment]
实在不行就科学的尽头是玄学，转用 `httpx` 请求，万一就好了也说不定。

**Comment by Nickszy** [comment]
换成httpx就好了，牛逼
增加代码如下
```
from bilibili_api import settings
settings.http_client = settings.HTTPClient.HTTPX
```

**Comment by blyc** [comment]
科学的尽头果真就是玄学艹
做bot每隔5秒调用一次`get_dynamic_page_info`获取最新动态，
更新16.2.0前一切正常，更新后频繁提示`ServerDisconnectedError('Server disconnected')`
尝试了修改ua，完善请求参数，频率从5降低到10试一次，延长请求超时，均无果
然后翻issues看到这个顺手试了一下，它好了...

**Comment by HentaiBoros** [comment]
> 科学的尽头果真就是玄学艹 做bot每隔5秒调用一次`get_dynamic_page_info`获取最新动态， 更新16.2.0前一切正常，更新后频繁提示`ServerDisconnectedError('Server disconnected')` 尝试了修改ua，完善请求参数，频率从5降低到10试一次，延长请求超时，均无果 然后翻issues看到这个顺手试了一下，它好了...

我也遇到了类似的问题，在实例化复数个包含 `get_dynamics_new()` 方法的对象并逐个调用时，有以下报错并且无法获取动态:
```
ERROR:root:get_document_list() error occurred
Traceback (most recent call last):
  File "D:\PythonProject\PostDownload\Server\bilibiliServer.py", line 293, in file_download_db_update
    await self.get_document_list()
  File "D:\PythonProject\PostDownload\Server\bilibiliServer.py", line 247, in get_document_list
    page = await u.get_dynamics_new(offset=offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\user.py", line 678, in get_dynamics_new
    await Api(**api, credential=self.credential).update_params(**params).result
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 553, in request
    async with session.request(**config) as resp:
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\client.py", line 605, in _request
    await resp.start(conn)
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
ERROR:root:Server disconnected
Traceback (most recent call last):
  File "D:\PythonProject\PostDownload\Server\bilibiliServer.py", line 293, in file_download_db_update
    await self.get_document_list()
  File "D:\PythonProject\PostDownload\Server\bilibiliServer.py", line 247, in get_document_list
    page = await u.get_dynamics_new(offset=offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\user.py", line 678, in get_dynamics_new
    await Api(**api, credential=self.credential).update_params(**params).result
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\bilibili_api\utils\network.py", line 553, in request
    async with session.request(**config) as resp:
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\client.py", line 605, in _request
    await resp.start(conn)
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\PostDownload\.venv\Lib\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```
具体表现为实例化 A, B, C, D 四个实例并逐个调用，A, C 调用结束后会有以上报错，B, D 因为该错误无法获取动态列表

设置 `settings.http_client = settings.HTTPClient.HTTPX` 也同样解决了我的这个问题，现能够正常获取所有动态列表
