### ISSUE TITLE
搜索时超时

### ISSUE THREAD

**Issue by creepebucket** [Nemo2011/bilibili-api#715]
**Python 版本：** 3.12.2

**模块版本：** 16.2.0

**运行环境：** Windows

---

使用搜索功能时出现超时错误:
```error
Traceback (most recent call last):
  File "D:\Desktop\我的项目\Python项目\redstone_daily\test.py", line 4, in <module>
    print(sync(search.search("奥利给")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\search.py", line 168, in search
    return await Api(**api).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 537, in request
    config = await self._prepare_request(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 458, in _prepare_request
    buvid3 = (await get_spi_buvid())["b_3"]
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 655, in get_spi_buvid
    return await Api(**API["info"]["spi"]).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 553, in request
    async with session.request(**config) as resp:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 504, in _request
    with timer:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```
能够访问bilibili以及进行搜索, 检查过 Credential 发现无误, 以任何形式执行搜索代码均超时

**Comment by z0z0r4** [comment]
timeout 就请参考下自己的环境了...真不熟

**Comment by creepebucket** [comment]
昨天还能用的...是不是啊b又弄了啥反爬机制...

**Comment by z0z0r4** [comment]
反爬哪有 timeout 的

**Comment by creepebucket** [comment]
哦谢谢,前天发现原因了,麻烦看一下我之前发的工单https://github.com/Nemo2011/bilibili-api/issues/716这个,是接口不稳定导致的,看到了就可以关工单了
