### ISSUE TITLE
[漏洞] 执行搜索时超时

### ISSUE THREAD

**Issue by creepebucket** [Nemo2011/bilibili-api#716]
### 错误信息: 

**Python 版本：** 3.12.2 / 3.10

**模块版本：** 16.2.0

**运行环境：** Windows

**模块路径：** `bilibili_api.xxxx`

**解释器：** 未知(很抱歉在这方面无法提供帮助,因为我未搜索到如何查看解释器)
**报错信息：**

```
Traceback (most recent call last):
  File "D:\Desktop\我的项目\Python项目\redstone_daily\test.py", line 4, in <module>
    print(sync(search.search("奥利给")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\search.py", line 168, in search
    return await Api(**api).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 537, in request
    config = await self._prepare_request(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 458, in _prepare_request
    buvid3 = (await get_spi_buvid())["b_3"]
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 655, in get_spi_buvid
    return await Api(**API["info"]["spi"]).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\bilibili_api\utils\network.py", line 553, in request
    async with session.request(**config) as resp:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 504, in _request
    with timer:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

**报错代码：**

```
TimeoutError
```

### 问题描述:  

任意方式执行搜索指令均出现超时错误

### 尝试过的解决方法:  

两个不同IP,机器与账户测试均出现此类问题

### 复现流程:  

执行任意搜索即可复现

### 预计报错原因:  

应该是搜索的接口不再是写的这个了, 改接口了

**Comment by creepebucket** [comment]
经核查的确是接口变更造成的

**Comment by creepebucket** [comment]
![50af2018368cf92464b7540a7a5f42f1](https://github.com/Nemo2011/bilibili-api/assets/158452230/6e3258b7-6208-4839-8256-4d9b9e2019a0)
抓包结果,希望能有所帮助

**Comment by StaticReasons** [comment]
楼上的图是我提供的（

呃呃，查看了隔壁一个仓库的[文档](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/search/search_request.md)，结合上面这张我刚抓的包可知现在的搜索接口早已修改成路径包含"/wbi"的带有wbi签名鉴权的接口，

而我们的库仍在使用没有wbi签名鉴权的旧接口，所以如果情况属实的话这个问题的出现就是必然的——旧接口早晚要被弃用。

我还不是熟悉这个仓库，不知道仓库里有没有可以辅助通过wbi鉴权的工具。。。。。我简单搜了一下没搜到wbi相关的东西。

可以考虑一下参考隔壁仓库的这篇[文档](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md)实现wbi签名的计算并尝试使用该签名调用新接口。

**Comment by StaticReasons** [comment]
啊我回来了

宝意思刚才发现这个库确实实现了wbi功能

然后我在自己项目里面实验了一下发现改一改data/api/search.json里面的参数就行了——在请求url里面"/web-interfaces"后插入"/wbi"字段，然后再添加“wbi"字段为true，就行了

由于我项目里面主要用search_by_type这个接口所以只试验了这一个，待会发PR，如果大家同意迁移到wbi接口的话，后面几个接口就麻烦你们帮忙调试啦！

**Comment by StaticReasons** [comment]
我是sb（）
原来没有wbi的接口又好了
那就先不管了
不过留个提醒 现在这个没有wbi的旧接口已经开始不稳定了！

**Comment by creepebucket** [comment]
不知道傻逼啊b在搞什么啊(恼

**Comment by mokurin000** [comment]
@creepebucket 现在wbi签名有做吗？我复现了搜索时超时

**Comment by z0z0r4** [comment]
一般遇到超时都是因为代理，原因未知，应该是调库产生的奇奇怪怪的问题=-=

**Comment by creepebucket** [comment]
a?我才初一啥都不懂
