### ISSUE TITLE
[提问] get_live_info() timeout

### ISSUE THREAD

**Issue by Pasumao** [Nemo2011/bilibili-api#721]
**Python 版本：** 3.10.13

**模块版本：** 最新

**运行环境：** Windows server

---
代码：
```
import asyncio
from bilibili_api import user


async def main() -> None:
    uid='488702476'
    u=user.User(uid)
    # 获取信息
    info = await u.get_live_info()
    # 打印信息
    print(info)


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```
报错：
```
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\bot\cq_pasubot\plugins\test.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\anaconda\envs\bot\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\Users\Administrator\Desktop\bot\cq_pasubot\plugins\test.py", line 9, in main
    info = await u.get_live_info()
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\user.py", line 439, in get_live_info
    await Api(**api, credential=self.credential).update_params(**params).result
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 537, in request
    config = await self._prepare_request(**kwargs)
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 441, in _prepare_request
    wbi_mixin_key = await get_mixin_key()
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 721, in get_mixin_key
    data = await get_nav()
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 691, in get_nav
    return await Api(credential=credential, **API["info"]["valid"]).result
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 537, in request
    config = await self._prepare_request(**kwargs)
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 458, in _prepare_request
    buvid3 = (await get_spi_buvid())["b_3"]
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 655, in get_spi_buvid
    return await Api(**API["info"]["spi"]).result
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 273, in result
    self.__result = await self.request()
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 173, in inner
    return await func(*args, **kwargs)
  File "D:\anaconda\envs\bot\lib\site-packages\bilibili_api\utils\network.py", line 553, in request
    async with session.request(**config) as resp:
  File "D:\anaconda\envs\bot\lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\bot\lib\site-packages\aiohttp\client.py", line 504, in _request
    with timer:
  File "D:\anaconda\envs\bot\lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```
别的也会有同样的问题，之前是能用的，也不知道什么时候开始不行的

**Comment by z0z0r4** [comment]
关掉代理试试看
