### ISSUE TITLE
[漏洞] parser好像只对async方法管用

### ISSUE THREAD

**Issue by nooblong** [Nemo2011/bilibili-api#724]
**Python 版本：** 3.11.5

**运行环境：** MacOS

**模块路径：** `bilibili_api.tools.parser`

**报错信息：**

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 160, in serialize_response
    return field.serialize(
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/_compat.py", line 147, in serialize
    return self._type_adapter.dump_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/type_adapter.py", line 333, in dump_python
    return self.serializer.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'method'>
```

**报错代码：**

```
请求：/video.Video(bvid=BV1ju411T7so).get_aid()
返回：Internal Server Error
如果get_aid()加上async就返回正确了
```

---
应该是返回了个函数没有执行

还有这个check_valid也会报错
```
/video.Video(bvid=BV1ju411T7so).get_info()?credential=Credential(sessdata="{{sessdata}}",bili_jct="{{bili_jct}}",buvid3={{buvid3}})

{
    "code": 3,
    "error": "未知错误 module 'bilibili_api' has no attribute 'check_valid'"
}
```
<img width="633" alt="image" src="https://github.com/Nemo2011/bilibili-api/assets/19368870/302071a4-ddfd-4bee-bd59-4c5305bb9ff3">

**Comment by Drelf2018** [comment]
待我一探究竟

**Comment by Drelf2018** [comment]
我这里正常返回
```json
{
    "code": 0,
    "data": {}
}
```
请问你的库版本是多少？

**Comment by Drelf2018** [comment]
实际上，执行时对函数类型进行了检测和分别调用，应该是不会出现 **_只对async方法管用_** 的情况的。

https://github.com/Nemo2011/bilibili-api/blob/48e6350ccd9596dadf65a6443927c9ccfcdfd6c6/bilibili_api/tools/parser/parser.py#L127-L133

**Comment by nooblong** [comment]
最新main分支
```python
aiohttp~=3.9.3
beautifulsoup4~=4.12.3
colorama~=0.4.6
lxml~=5.1.0
pyyaml~=6.0
brotli~=1.1.0
httpx~=0.26.0
qrcode~=7.4.2
requests~=2.31.0
APScheduler~=3.10.4
rsa~=4.9
pillow~=10.2.0
tqdm~=4.66.2
yarl~=1.9.4
pycryptodomex~=3.20.0
qrcode_terminal~=0.8
uvicorn~=0.29.0
fastapi~=0.110.0

代码:
from bilibili_api.tools.parser import get_fastapi
import uvicorn

if __name__ == "__main__":
    uvicorn.run(get_fastapi(), host="0.0.0.0", port=9000)
```
我重新装了个python3.11.7环境，也和你返回一样的了，可是正常返回不应该是
/video.Video(bvid=BV1ju411T7so).get_aid()
```
{
    "code": 0,
    "data": 534679892
}
```
你试一下
/channel_series.ChannelSeries(id_= 1845727,uid=148524702,type_=channel_series.ChannelSeriesType.SEASON:parse).get_meta()
