### ISSUE TITLE
[提问] 调用开启直播接口时报csrf 校验失败异常

### ISSUE THREAD

**Issue by guch8017** [Nemo2011/bilibili-api#729]
**Python 版本：** 3.10.8

**模块版本：** 16.2.0（从git安装，应该是16.2.1但是版本信息未更新到代码）

**运行环境：** Windows

---

<img width="566" alt="{DF9B709A-F0C8-4e99-8E31-3B6692EFADB5}" src="https://github.com/Nemo2011/bilibili-api/assets/38173059/4093e215-8072-443a-b026-1aecb198d514">

尝试通过API开启直播并获取推流码，但是相关接口返回鉴权错误。已确定凭据信息是有效的，同时网页端开启未出现问题，其余需要鉴权的接口也能正常工作。

**Comment by z0z0r4** [comment]
能提供下报错堆栈吗？

**Comment by guch8017** [comment]
没问题的，以下是traceback：


```bash
Valid:  True
[Request][2024-03-25 16:03:26,908] 激活 buvid3 成功
Room ID:  123456[HIDDEN]
Traceback (most recent call last):
  File "D:\Workspace\BiliLive\main.py", line 34, in <module>
    start_live()
  File "D:\Workspace\BiliLive\main.py", line 28, in start_live
    ret = asyncio.run(room.stop())
  File "F:\Users\ASUS\.conda\envs\server\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "F:\Users\ASUS\.conda\envs\server\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\Users\ASUS\.conda\envs\server\lib\site-packages\bilibili_api\live.py", line 160, in stop
    await Api(**api, credential=self.credential).update_params(**params).result
  File "F:\Users\ASUS\.conda\envs\server\lib\site-packages\bilibili_api\utils\network.py", line 274, in result
    self.__result = await self.request()
  File "F:\Users\ASUS\.conda\envs\server\lib\site-packages\bilibili_api\utils\network.py", line 174, in inner
    return await func(*args, **kwargs)
  File "F:\Users\ASUS\.conda\envs\server\lib\site-packages\bilibili_api\utils\network.py", line 563, in request
    real_data = self._process_response(
  File "F:\Users\ASUS\.conda\envs\server\lib\site-packages\bilibili_api\utils\network.py", line 610, in _process_response
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-111，信息：csrf 校验失败。
{'code': -111, 'message': 'csrf 校验失败', 'ttl': 1}
```
