### ISSUE TITLE
[漏洞] {在获取评论时，当页数超过252页时出现-400报错}

### ISSUE THREAD

**Issue by Munbo123** [Nemo2011/bilibili-api#798]
**Python 版本：** 3.12.5

**模块版本：** 16.2.0 

**运行环境：** Windows 

**模块路径：** `bilibili_api.xxxx`

**解释器：** cpython

**报错信息：**

```
Traceback (most recent call last):
  File "C:\Users\19722\Desktop\Coding\Languages\Python\test1.py", line 18, in <module>
    sync(main())
  File "e:\Programming\Python\python312\Lib\site-packages\bilibili_api\utils\sync.py", line 33, in sync
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Programming\Python\python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\19722\Desktop\Coding\Languages\Python\test1.py", line 14, in main
    c = await comment.get_comments('BV16i42167pe', comment.CommentResourceType.VIDEO, page,credential=credential)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Programming\Python\python312\Lib\site-packages\bilibili_api\comment.py", line 411, in get_comments   
    return await Api(**api, credential=credential).update_params(**params).result
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Programming\Python\python312\Lib\site-packages\bilibili_api\utils\network.py", line 273, in result   
    self.__result = await self.request()
                    ^^^^^^^^^^^^^^^^^^^^
  File "e:\Programming\Python\python312\Lib\site-packages\bilibili_api\utils\network.py", line 173, in inner    
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Programming\Python\python312\Lib\site-packages\bilibili_api\utils\network.py", line 558, in request  
    real_data = self._process_response(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Programming\Python\python312\Lib\site-packages\bilibili_api\utils\network.py", line 603, in _process_response
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-400，信息：max offset exceeded。
{'code': -400, 'message': 'max offset exceeded', 'ttl': 1}
```

**报错代码：**

```
from bilibili_api import comment, sync
from bilibili_api import Credential

SESSDATA = '我这里使用了我自己的数据，下同'
bili_jct = ''
buvid3 = ''

credential = Credential(sessdata=SESSDATA, bili_jct=bili_jct, buvid3=buvid3)
async def main():
    page = 252      #这个数字是251的时候可以正常获取，到了252的时候就出现错误，已经验证，原视频的评论数量没有到头（大约还有三分之一没有被获取）
    c = await comment.get_comments('BV16i42167pe', comment.CommentResourceType.VIDEO, page,credential=credential)
    print(c)


sync(main())
```

---

在爬取有较多评论的视频时，当爬取的页数达到252时，会出现-400  max offset exceeded报错，而251及以下都可以正常获取，经过多个有较多评论的视频验证，该现象普遍存在

**Comment by Nemo2011** [comment]
估计是触碰到底层限制了，只读取252之前，就像关注页面锁5页。而且这个还是旧接口。

**Comment by Nemo2011** [comment]
诶，之前有一个issue #747 是400页

**Comment by Nemo2011** [comment]
貌似是削到251了，#747 的代码我也跑不了400页了。

**Comment by Munbo123** [comment]
这样嘛，那是否有其它办法获取更早的评论呢，比如说新的接口，还是说这是b站刻意做出的限制？🤔

**Comment by wangling6666** [comment]
请问解决了吗

**Comment by Littlefish12138** [comment]
这个-400 max offset exceeded的触发条件是什么？

我使用DrissionPage模拟浏览器下滑+监听根评论网络请求+SessionPage请求二级评论的方法，对评论较多的视频做了测试，并没有触发这个。我在2026-03-07 00:15针对视频[BV1MN4y177PB](https://www.bilibili.com/video/BV1MN4y177PB)，做了测试，b站显示的总评论数65521左右，爬取到的总评论数是65529，其中根评论(一级评论)数量为49462

我感觉至少模拟浏览器操作是可以到底的

**Comment by yue6121** [comment]
wbi新接口，没有这个限制
