### ISSUE TITLE
【提问】获取自动循环获取用户投稿视频信息失败

### ISSUE THREAD

**Issue by nicliuqi** [Nemo2011/bilibili-api#80]
**Python 版本： 3.8.6

**模块版本：3.1.3

**运行环境：Linux/MacOS

---

在release3.1.3中，可以通过调用user.get_videos_g({uid})来获取用户的所有投稿视频信息，但在2022-09-21 18:00后，使用这个方法开始开始出现异常，以下是我在MacOS上执行失败的一段错误日志:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bilibili_api/user.py", line 118, in get_videos_g
    data = get_videos_raw(uid=uid, order=order, pn=page, verify=verify)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bilibili_api/user.py", line 158, in get_videos_g
    data = utils.get(url=api["url"], params=params, cookies=verify.get_cookies())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bilibili_api/utils.py", line 418, in get
    resp = request("GET", url=url, params=params, cookies=cookies, headers=headers, data_type=date_type, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bilibili_api/utils.py", line 394, in request
    raise exceptions.BilibiliException(con["code"], msg)
bilibili_api.exceptions.BilibiliException: 错误代码：-401, 信息：非法访问

考虑到bilibili版本迭代速度过快，而release 3.1.3一直以来都能满足我们的服务需求，所以想请教下不切换版本的情况下是否还能获取到一个用户所发布的所有投稿信息

**Comment by Nemo2011** [comment]
多试几次，可以成功的。可能是因为现在 B 站 API 访问 https 验证加强，aiohttp 访问的时候会显示 `ssl` 错误。自己在 `request_settings` 中设置一下是否验证 `ssl` 应该就可以了。

**Comment by nicliuqi** [comment]
这种调用更像SDK吧  目前我在两个服务都开了定时任务来检查用户上传的视频是否过审，两个服务都异常超过6天了
是否能提供一个稳定的获取方式呢

**Comment by Nemo2011** [comment]
那还是更新到最新版本吧，目前也不知道是什么问题，最新版本不会出现"非法访问"情况。

**Comment by nicliuqi** [comment]
最新版本获取用户的所有投稿是调用bilibili_api.user.get_videos()吗，这个接口貌似对数据进行了分页，请问每页的最大值是多少呢

**Comment by Nemo2011** [comment]
最新版本是先初始化 user.User 类，然后调用 User.get_videos 方法就可以了，每页最大 50 个视频

**Comment by Nemo2011** [comment]
尽量不要快速调用同一个 API, 否则会风控

**Comment by nicliuqi** [comment]
一个小时内调10次以内应该没关系吧

**Comment by Nemo2011** [comment]
应该不会风控
