### ISSUE TITLE
[提问] 为什么这个图文获取不到module_content

### ISSUE THREAD

**Issue by wwkk2580** [Nemo2011/bilibili-api#825]
**Python 版本：** 3.9.13

**模块版本：** 16.2.0

**运行环境：** Windows 

---
代码
````
from bilibili_api import opus

o = opus.Opus(985251045184634900)

a=o.markdown()

print(a)
````

###  链接：https://www.bilibili.com/opus/985251045184634900
为什么这个图文获取不到module_content

```
PS E:\hellopython> & E:/data/python39/python.exe e:/hellopython/python/B站.py
Traceback (most recent call last):
  File "e:\hellopython\python\B站.py", line 20, in <module>
    a=o.markdown()
  File "E:\data\python39\lib\site-packages\bilibili_api\opus.py", line 149, in markdown
    for para in content["module_content"]["paragraphs"]:
KeyError: 'module_content'
````

**Comment by snowman** [comment]
返回的数据
```json
{
  "modules": [
    {
      "module_title": { ... },
      "module_type": "MODULE_TYPE_TITLE"
    },
    {
      "module_author": { ... },
      "module_type": "MODULE_TYPE_AUTHOR"
    },
    {
      "module_collection": { ... },
      "module_type": "MODULE_TYPE_COLLECTION"
    },
    {
      "module_content": {
        "paragraphs": [...]
      },
      "module_type": "MODULE_TYPE_CONTENT"
    }
  ]
}
```

```diff
bilibili_api/opus.py
-        title, author, content = self.__info["modules"][:3]
+        title, author, _, content = self.__info["modules"][:4]
```

因为返回的数据格式不匹配, 这里 hard code 就不够 flexibility, 有可能将来还会报错
所以不要直接用数组索引

```python
for module in self.__info["modules"]:
  if "module_title" in module:
    title = module
    continue

  if "module_author" in module:
    author = module
    continue

  if "module_content" in module:
    content = module
    continue

  if title and author and content:
    break
```

**Comment by snowman** [comment]
返回的数据
```json
{
  "modules": [
    {
      "module_title": { ... },
      "module_type": "MODULE_TYPE_TITLE"
    },
    {
      "module_author": { ... },
      "module_type": "MODULE_TYPE_AUTHOR"
    },
    {
      "module_collection": { ... },
      "module_type": "MODULE_TYPE_COLLECTION"
    },
    {
      "module_content": {
        "paragraphs": [...]
      },
      "module_type": "MODULE_TYPE_CONTENT"
    },
    ...
  ]
}
```

```diff
bilibili_api/opus.py
-        title, author, content = self.__info["modules"][:3]
+        title, author, _, content = self.__info["modules"][:4]
```

因为返回的数据格式不匹配, 这里 hard code 就不够 flexibility, 有可能将来还会报错
所以不要直接用数组索引

```python
for module in self.__info["modules"]:
  if "module_title" in module:
    title = module
    continue

  if "module_author" in module:
    author = module
    continue

  if "module_content" in module:
    content = module
    continue

  if title and author and content:
    break
```

**Comment by wwkk2580** [comment]
好的，谢谢
