### ISSUE TITLE
sync函数近期更改，该如何调用？

### ISSUE THREAD

**Issue by TZFC** [Nemo2011/bilibili-api#860]
**Python 版本：** 3.11.10

**模块版本：** 可用版本：16.1.1 报错版本：16.3.0

**运行环境：** Linux

---

我在16.1.1版本时可以这么使用sync:
sync(asyncio.gather(*[some_coroutine(), some_other_coroutine(), 
                        refresh_credentials_loop(credential_dict=credential_dict, database=mydb)
                        ))
更新到16.3.0之后会报错sync 22行：
no running event loop

看起来16.1.1与16.3.0之间sync进行了比较大的改变。请问现在该如何正确使用呢？

**Comment by LondonClass** [comment]
我改的。能看一下具体的报错信息吗？能不能把完整的报错信息截图发出来

**Comment by TZFC** [comment]
```
if __name__ == "__main__":
    sync(asyncio.gather(*[roomInfos[room_id]['live_danmaku'].connect() for room_id in ROOM_IDS],
                        refresh_credentials_loop(credential_dict=credential_dict, database=mydb)
                        ))
```
其中roomInfos[room_id]['live_danmaku'] 是一个LiveDanmaku类

**Comment by TZFC** [comment]
报错信息为：
```
Traceback (most recent call last):
  File "/home/ubuntu/BiliLiveManager/test/lib/python3.11/site-packages/bilibili_api/utils/sync.py", line 22, in sync
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/BiliLiveManager/master.py", line 168, in <module>
    sync(asyncio.gather(*[roomInfos[room_id]['live_danmaku'].connect() for room_id in ROOM_IDS],
  File "/home/ubuntu/BiliLiveManager/test/lib/python3.11/site-packages/bilibili_api/utils/sync.py", line 24, in sync
    return asyncio.run(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 89, in run
    raise ValueError("a coroutine was expected, got {!r}".format(coro))
ValueError: a coroutine was expected, got <_GatheringFuture pending>
sys:1: RuntimeWarning: coroutine 'refresh_credentials_loop' was never awaited
sys:1: RuntimeWarning: coroutine 'LiveDanmaku.connect' was never awaited
```
使用改之前的sync()版本就不会报错

**Comment by z0z0r4** [comment]
https://docs.python.org/zh-cn/3.13/library/asyncio-runner.html#asyncio.run

`asyncio.gather` 给的是 `asyncio.tasks._GatheringFuture`，而 `asyncio.run` 是不认的
